// Code generated by protoc-gen-go.
// source: poseidonstats.proto
// DO NOT EDIT!

/*
Package stats is a generated protocol buffer package.

It is generated from these files:
	poseidonstats.proto

It has these top-level messages:
	NodeStats
	NodeStatsResponse
	PodStats
	PodStatsResponse
*/
package stats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeStatsResponseType int32

const (
	NodeStatsResponseType_NODE_STATS_OK  NodeStatsResponseType = 0
	NodeStatsResponseType_NODE_NOT_FOUND NodeStatsResponseType = 1
)

var NodeStatsResponseType_name = map[int32]string{
	0: "NODE_STATS_OK",
	1: "NODE_NOT_FOUND",
}
var NodeStatsResponseType_value = map[string]int32{
	"NODE_STATS_OK":  0,
	"NODE_NOT_FOUND": 1,
}

func (x NodeStatsResponseType) String() string {
	return proto.EnumName(NodeStatsResponseType_name, int32(x))
}
func (NodeStatsResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PodStatsResponseType int32

const (
	PodStatsResponseType_POD_STATS_OK  PodStatsResponseType = 0
	PodStatsResponseType_POD_NOT_FOUND PodStatsResponseType = 1
)

var PodStatsResponseType_name = map[int32]string{
	0: "POD_STATS_OK",
	1: "POD_NOT_FOUND",
}
var PodStatsResponseType_value = map[string]int32{
	"POD_STATS_OK":  0,
	"POD_NOT_FOUND": 1,
}

func (x PodStatsResponseType) String() string {
	return proto.EnumName(PodStatsResponseType_name, int32(x))
}
func (PodStatsResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NodeStats struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	// CPU stats in millicores.
	CpuAllocatable uint64 `protobuf:"varint,2,opt,name=cpu_allocatable,json=cpuAllocatable" json:"cpu_allocatable,omitempty"`
	CpuCapacity    uint64 `protobuf:"varint,3,opt,name=cpu_capacity,json=cpuCapacity" json:"cpu_capacity,omitempty"`
	CpuReservation uint64 `protobuf:"varint,4,opt,name=cpu_reservation,json=cpuReservation" json:"cpu_reservation,omitempty"`
	CpuUtilization uint64 `protobuf:"varint,5,opt,name=cpu_utilization,json=cpuUtilization" json:"cpu_utilization,omitempty"`
	// Memory stats in Kb.
	MemAllocatable uint64 `protobuf:"varint,6,opt,name=mem_allocatable,json=memAllocatable" json:"mem_allocatable,omitempty"`
	MemCapacity    uint64 `protobuf:"varint,7,opt,name=mem_capacity,json=memCapacity" json:"mem_capacity,omitempty"`
	MemReservation uint64 `protobuf:"varint,8,opt,name=mem_reservation,json=memReservation" json:"mem_reservation,omitempty"`
	MemUtilization uint64 `protobuf:"varint,9,opt,name=mem_utilization,json=memUtilization" json:"mem_utilization,omitempty"`
}

func (m *NodeStats) Reset()                    { *m = NodeStats{} }
func (m *NodeStats) String() string            { return proto.CompactTextString(m) }
func (*NodeStats) ProtoMessage()               {}
func (*NodeStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeStats) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeStats) GetCpuAllocatable() uint64 {
	if m != nil {
		return m.CpuAllocatable
	}
	return 0
}

func (m *NodeStats) GetCpuCapacity() uint64 {
	if m != nil {
		return m.CpuCapacity
	}
	return 0
}

func (m *NodeStats) GetCpuReservation() uint64 {
	if m != nil {
		return m.CpuReservation
	}
	return 0
}

func (m *NodeStats) GetCpuUtilization() uint64 {
	if m != nil {
		return m.CpuUtilization
	}
	return 0
}

func (m *NodeStats) GetMemAllocatable() uint64 {
	if m != nil {
		return m.MemAllocatable
	}
	return 0
}

func (m *NodeStats) GetMemCapacity() uint64 {
	if m != nil {
		return m.MemCapacity
	}
	return 0
}

func (m *NodeStats) GetMemReservation() uint64 {
	if m != nil {
		return m.MemReservation
	}
	return 0
}

func (m *NodeStats) GetMemUtilization() uint64 {
	if m != nil {
		return m.MemUtilization
	}
	return 0
}

type NodeStatsResponse struct {
	Type     NodeStatsResponseType `protobuf:"varint,1,opt,name=type,enum=stats.NodeStatsResponseType" json:"type,omitempty"`
	Hostname string                `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *NodeStatsResponse) Reset()                    { *m = NodeStatsResponse{} }
func (m *NodeStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeStatsResponse) ProtoMessage()               {}
func (*NodeStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeStatsResponse) GetType() NodeStatsResponseType {
	if m != nil {
		return m.Type
	}
	return NodeStatsResponseType_NODE_STATS_OK
}

func (m *NodeStatsResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type PodStats struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Hostname  string `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	// CPU stats in millicores.
	CpuLimit   uint64 `protobuf:"varint,4,opt,name=cpu_limit,json=cpuLimit" json:"cpu_limit,omitempty"`
	CpuRequest uint64 `protobuf:"varint,5,opt,name=cpu_request,json=cpuRequest" json:"cpu_request,omitempty"`
	CpuUsage   uint64 `protobuf:"varint,6,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
	// Memory stats in Kb.
	MemLimit            uint64  `protobuf:"varint,7,opt,name=mem_limit,json=memLimit" json:"mem_limit,omitempty"`
	MemRequest          uint64  `protobuf:"varint,8,opt,name=mem_request,json=memRequest" json:"mem_request,omitempty"`
	MemUsage            uint64  `protobuf:"varint,9,opt,name=mem_usage,json=memUsage" json:"mem_usage,omitempty"`
	MemWorkingSet       uint64  `protobuf:"varint,10,opt,name=mem_working_set,json=memWorkingSet" json:"mem_working_set,omitempty"`
	MemPageFaults       uint64  `protobuf:"varint,11,opt,name=mem_page_faults,json=memPageFaults" json:"mem_page_faults,omitempty"`
	MemPageFaultsRate   float64 `protobuf:"fixed64,12,opt,name=mem_page_faults_rate,json=memPageFaultsRate" json:"mem_page_faults_rate,omitempty"`
	MajorPageFaults     uint64  `protobuf:"varint,13,opt,name=major_page_faults,json=majorPageFaults" json:"major_page_faults,omitempty"`
	MajorPageFaultsRate float64 `protobuf:"fixed64,14,opt,name=major_page_faults_rate,json=majorPageFaultsRate" json:"major_page_faults_rate,omitempty"`
	// Network stats in Kb.
	NetRx           uint64  `protobuf:"varint,15,opt,name=net_rx,json=netRx" json:"net_rx,omitempty"`
	NetRxErrors     uint64  `protobuf:"varint,16,opt,name=net_rx_errors,json=netRxErrors" json:"net_rx_errors,omitempty"`
	NetRxErrorsRate float64 `protobuf:"fixed64,17,opt,name=net_rx_errors_rate,json=netRxErrorsRate" json:"net_rx_errors_rate,omitempty"`
	NetRxRate       float64 `protobuf:"fixed64,18,opt,name=net_rx_rate,json=netRxRate" json:"net_rx_rate,omitempty"`
	NetTx           uint64  `protobuf:"varint,19,opt,name=net_tx,json=netTx" json:"net_tx,omitempty"`
	NetTxErrors     uint64  `protobuf:"varint,20,opt,name=net_tx_errors,json=netTxErrors" json:"net_tx_errors,omitempty"`
	NetTxErrorsRate float64 `protobuf:"fixed64,21,opt,name=net_tx_errors_rate,json=netTxErrorsRate" json:"net_tx_errors_rate,omitempty"`
	NetTxRate       float64 `protobuf:"fixed64,22,opt,name=net_tx_rate,json=netTxRate" json:"net_tx_rate,omitempty"`
}

func (m *PodStats) Reset()                    { *m = PodStats{} }
func (m *PodStats) String() string            { return proto.CompactTextString(m) }
func (*PodStats) ProtoMessage()               {}
func (*PodStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PodStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodStats) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodStats) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PodStats) GetCpuLimit() uint64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *PodStats) GetCpuRequest() uint64 {
	if m != nil {
		return m.CpuRequest
	}
	return 0
}

func (m *PodStats) GetCpuUsage() uint64 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *PodStats) GetMemLimit() uint64 {
	if m != nil {
		return m.MemLimit
	}
	return 0
}

func (m *PodStats) GetMemRequest() uint64 {
	if m != nil {
		return m.MemRequest
	}
	return 0
}

func (m *PodStats) GetMemUsage() uint64 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *PodStats) GetMemWorkingSet() uint64 {
	if m != nil {
		return m.MemWorkingSet
	}
	return 0
}

func (m *PodStats) GetMemPageFaults() uint64 {
	if m != nil {
		return m.MemPageFaults
	}
	return 0
}

func (m *PodStats) GetMemPageFaultsRate() float64 {
	if m != nil {
		return m.MemPageFaultsRate
	}
	return 0
}

func (m *PodStats) GetMajorPageFaults() uint64 {
	if m != nil {
		return m.MajorPageFaults
	}
	return 0
}

func (m *PodStats) GetMajorPageFaultsRate() float64 {
	if m != nil {
		return m.MajorPageFaultsRate
	}
	return 0
}

func (m *PodStats) GetNetRx() uint64 {
	if m != nil {
		return m.NetRx
	}
	return 0
}

func (m *PodStats) GetNetRxErrors() uint64 {
	if m != nil {
		return m.NetRxErrors
	}
	return 0
}

func (m *PodStats) GetNetRxErrorsRate() float64 {
	if m != nil {
		return m.NetRxErrorsRate
	}
	return 0
}

func (m *PodStats) GetNetRxRate() float64 {
	if m != nil {
		return m.NetRxRate
	}
	return 0
}

func (m *PodStats) GetNetTx() uint64 {
	if m != nil {
		return m.NetTx
	}
	return 0
}

func (m *PodStats) GetNetTxErrors() uint64 {
	if m != nil {
		return m.NetTxErrors
	}
	return 0
}

func (m *PodStats) GetNetTxErrorsRate() float64 {
	if m != nil {
		return m.NetTxErrorsRate
	}
	return 0
}

func (m *PodStats) GetNetTxRate() float64 {
	if m != nil {
		return m.NetTxRate
	}
	return 0
}

type PodStatsResponse struct {
	Type      PodStatsResponseType `protobuf:"varint,1,opt,name=type,enum=stats.PodStatsResponseType" json:"type,omitempty"`
	Name      string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Namespace string               `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *PodStatsResponse) Reset()                    { *m = PodStatsResponse{} }
func (m *PodStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PodStatsResponse) ProtoMessage()               {}
func (*PodStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PodStatsResponse) GetType() PodStatsResponseType {
	if m != nil {
		return m.Type
	}
	return PodStatsResponseType_POD_STATS_OK
}

func (m *PodStatsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodStatsResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeStats)(nil), "stats.NodeStats")
	proto.RegisterType((*NodeStatsResponse)(nil), "stats.NodeStatsResponse")
	proto.RegisterType((*PodStats)(nil), "stats.PodStats")
	proto.RegisterType((*PodStatsResponse)(nil), "stats.PodStatsResponse")
	proto.RegisterEnum("stats.NodeStatsResponseType", NodeStatsResponseType_name, NodeStatsResponseType_value)
	proto.RegisterEnum("stats.PodStatsResponseType", PodStatsResponseType_name, PodStatsResponseType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PoseidonStats service

type PoseidonStatsClient interface {
	ReceiveNodeStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceiveNodeStatsClient, error)
	ReceivePodStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceivePodStatsClient, error)
}

type poseidonStatsClient struct {
	cc *grpc.ClientConn
}

func NewPoseidonStatsClient(cc *grpc.ClientConn) PoseidonStatsClient {
	return &poseidonStatsClient{cc}
}

func (c *poseidonStatsClient) ReceiveNodeStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceiveNodeStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PoseidonStats_serviceDesc.Streams[0], c.cc, "/stats.PoseidonStats/ReceiveNodeStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &poseidonStatsReceiveNodeStatsClient{stream}
	return x, nil
}

type PoseidonStats_ReceiveNodeStatsClient interface {
	Send(*NodeStats) error
	Recv() (*NodeStatsResponse, error)
	grpc.ClientStream
}

type poseidonStatsReceiveNodeStatsClient struct {
	grpc.ClientStream
}

func (x *poseidonStatsReceiveNodeStatsClient) Send(m *NodeStats) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poseidonStatsReceiveNodeStatsClient) Recv() (*NodeStatsResponse, error) {
	m := new(NodeStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *poseidonStatsClient) ReceivePodStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceivePodStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PoseidonStats_serviceDesc.Streams[1], c.cc, "/stats.PoseidonStats/ReceivePodStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &poseidonStatsReceivePodStatsClient{stream}
	return x, nil
}

type PoseidonStats_ReceivePodStatsClient interface {
	Send(*PodStats) error
	Recv() (*PodStatsResponse, error)
	grpc.ClientStream
}

type poseidonStatsReceivePodStatsClient struct {
	grpc.ClientStream
}

func (x *poseidonStatsReceivePodStatsClient) Send(m *PodStats) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poseidonStatsReceivePodStatsClient) Recv() (*PodStatsResponse, error) {
	m := new(PodStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PoseidonStats service

type PoseidonStatsServer interface {
	ReceiveNodeStats(PoseidonStats_ReceiveNodeStatsServer) error
	ReceivePodStats(PoseidonStats_ReceivePodStatsServer) error
}

func RegisterPoseidonStatsServer(s *grpc.Server, srv PoseidonStatsServer) {
	s.RegisterService(&_PoseidonStats_serviceDesc, srv)
}

func _PoseidonStats_ReceiveNodeStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoseidonStatsServer).ReceiveNodeStats(&poseidonStatsReceiveNodeStatsServer{stream})
}

type PoseidonStats_ReceiveNodeStatsServer interface {
	Send(*NodeStatsResponse) error
	Recv() (*NodeStats, error)
	grpc.ServerStream
}

type poseidonStatsReceiveNodeStatsServer struct {
	grpc.ServerStream
}

func (x *poseidonStatsReceiveNodeStatsServer) Send(m *NodeStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poseidonStatsReceiveNodeStatsServer) Recv() (*NodeStats, error) {
	m := new(NodeStats)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PoseidonStats_ReceivePodStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoseidonStatsServer).ReceivePodStats(&poseidonStatsReceivePodStatsServer{stream})
}

type PoseidonStats_ReceivePodStatsServer interface {
	Send(*PodStatsResponse) error
	Recv() (*PodStats, error)
	grpc.ServerStream
}

type poseidonStatsReceivePodStatsServer struct {
	grpc.ServerStream
}

func (x *poseidonStatsReceivePodStatsServer) Send(m *PodStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poseidonStatsReceivePodStatsServer) Recv() (*PodStats, error) {
	m := new(PodStats)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PoseidonStats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.PoseidonStats",
	HandlerType: (*PoseidonStatsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveNodeStats",
			Handler:       _PoseidonStats_ReceiveNodeStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceivePodStats",
			Handler:       _PoseidonStats_ReceivePodStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "poseidonstats.proto",
}

func init() { proto.RegisterFile("poseidonstats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x95, 0x5d, 0x4f, 0xdb, 0x3e,
	0x14, 0xc6, 0x49, 0x29, 0xfd, 0x37, 0xa7, 0xb4, 0x4d, 0xcd, 0xcb, 0x3f, 0x02, 0xb4, 0xb1, 0x5e,
	0x6c, 0x15, 0x93, 0x00, 0xc1, 0xe5, 0xa4, 0x49, 0x68, 0x85, 0x9b, 0x4d, 0x6d, 0x95, 0x06, 0xed,
	0x32, 0x32, 0xe1, 0xac, 0xcb, 0xd6, 0xbc, 0x2c, 0x76, 0x18, 0xec, 0x6a, 0x1f, 0x63, 0xdf, 0x6f,
	0x5f, 0x64, 0xb2, 0x9d, 0xb8, 0x49, 0x80, 0xab, 0xd6, 0xc7, 0xbf, 0xf3, 0xf8, 0x91, 0x9f, 0x1e,
	0x17, 0xb6, 0x92, 0x98, 0x61, 0x70, 0x1b, 0x47, 0x8c, 0x53, 0xce, 0x8e, 0x93, 0x34, 0xe6, 0x31,
	0xd9, 0x90, 0x8b, 0xe1, 0xdf, 0x06, 0x98, 0x93, 0xf8, 0x16, 0xe7, 0x62, 0x45, 0xf6, 0xa0, 0xfd,
	0x35, 0x66, 0x3c, 0xa2, 0x21, 0xda, 0xc6, 0xa1, 0x31, 0x32, 0x1d, 0xbd, 0x26, 0x6f, 0xa0, 0xef,
	0x27, 0x99, 0x47, 0x97, 0xcb, 0xd8, 0xa7, 0x9c, 0xde, 0x2c, 0xd1, 0x6e, 0x1c, 0x1a, 0xa3, 0xa6,
	0xd3, 0xf3, 0x93, 0xec, 0x62, 0x55, 0x25, 0xaf, 0x60, 0x53, 0x80, 0x3e, 0x4d, 0xa8, 0x1f, 0xf0,
	0x07, 0x7b, 0x5d, 0x52, 0x1d, 0x3f, 0xc9, 0x3e, 0xe4, 0xa5, 0x42, 0x2b, 0x45, 0x86, 0xe9, 0x1d,
	0xe5, 0x41, 0x1c, 0xd9, 0x4d, 0xad, 0xe5, 0xac, 0xaa, 0x05, 0x98, 0xf1, 0x60, 0x19, 0xfc, 0x52,
	0xe0, 0x86, 0x06, 0xaf, 0x57, 0x55, 0x01, 0x86, 0x18, 0x56, 0xdc, 0xb5, 0x14, 0x18, 0x62, 0x58,
	0x73, 0x27, 0x40, 0xed, 0xee, 0x3f, 0xe5, 0x2e, 0xc4, 0xb0, 0xec, 0x4e, 0x20, 0x65, 0x77, 0x6d,
	0xad, 0x55, 0x73, 0x27, 0xc0, 0xb2, 0x3b, 0x53, 0x83, 0x25, 0x77, 0x43, 0x0a, 0x03, 0x7d, 0xc9,
	0x0e, 0xb2, 0x24, 0x8e, 0x18, 0x92, 0x53, 0x68, 0xf2, 0x87, 0x44, 0x5d, 0x74, 0xef, 0xec, 0xe0,
	0x58, 0xa5, 0xf3, 0x88, 0x73, 0x1f, 0x12, 0x74, 0x24, 0x59, 0x89, 0xa7, 0x51, 0x8d, 0x67, 0xf8,
	0xbb, 0x05, 0xed, 0x59, 0x7c, 0xab, 0x72, 0x24, 0xd0, 0x2c, 0x65, 0x28, 0xbf, 0x93, 0x03, 0x30,
	0xc5, 0x27, 0x4b, 0xa8, 0x5f, 0x74, 0xaf, 0x0a, 0x15, 0xe9, 0xf5, 0x5a, 0xf2, 0xfb, 0x60, 0x8a,
	0x10, 0x96, 0x41, 0x18, 0xf0, 0x3c, 0xa7, 0xb6, 0x9f, 0x64, 0x9f, 0xc4, 0x9a, 0xbc, 0x84, 0x8e,
	0x8a, 0xf2, 0x47, 0x86, 0x8c, 0xe7, 0xe9, 0x80, 0x8c, 0x51, 0x56, 0x8a, 0xee, 0x8c, 0xd1, 0x45,
	0x91, 0x89, 0xe8, 0xbe, 0x16, 0x6b, 0xb1, 0x29, 0x6e, 0x50, 0x49, 0xab, 0x28, 0xda, 0x21, 0x86,
	0x5a, 0x5a, 0xe5, 0xa0, 0xa4, 0x55, 0x06, 0x20, 0x33, 0xd0, 0xd2, 0xf2, 0xfe, 0xa5, 0xb4, 0xa9,
	0xbb, 0x95, 0xf4, 0x6b, 0x15, 0xce, 0xcf, 0x38, 0xfd, 0x1e, 0x44, 0x0b, 0x8f, 0x21, 0xb7, 0x41,
	0x22, 0xdd, 0x10, 0xc3, 0xcf, 0xaa, 0x3a, 0x47, 0x5e, 0x70, 0x09, 0x5d, 0xa0, 0xf7, 0x85, 0x66,
	0x4b, 0xce, 0xec, 0x8e, 0xe6, 0x66, 0x74, 0x81, 0x57, 0xb2, 0x48, 0x4e, 0x60, 0xbb, 0xc6, 0x79,
	0x29, 0xe5, 0x68, 0x6f, 0x1e, 0x1a, 0x23, 0xc3, 0x19, 0x54, 0x60, 0x87, 0x72, 0x24, 0x47, 0x30,
	0x08, 0xe9, 0xb7, 0x38, 0xad, 0x48, 0x77, 0xa5, 0x74, 0x5f, 0x6e, 0x94, 0xc4, 0xcf, 0x61, 0xf7,
	0x11, 0xab, 0xe4, 0x7b, 0x52, 0x7e, 0xab, 0xd6, 0x20, 0x0f, 0xd8, 0x81, 0x56, 0x84, 0xdc, 0x4b,
	0xef, 0xed, 0xbe, 0x54, 0xdd, 0x88, 0x90, 0x3b, 0xf7, 0x64, 0x08, 0x5d, 0x55, 0xf6, 0x30, 0x4d,
	0xe3, 0x94, 0xd9, 0x96, 0xfa, 0x89, 0xcb, 0xdd, 0x4b, 0x59, 0x22, 0x6f, 0x81, 0x54, 0x18, 0x75,
	0xd6, 0x40, 0x9e, 0xd5, 0x2f, 0x81, 0xf2, 0x9c, 0x17, 0xd0, 0xc9, 0x61, 0x49, 0x11, 0x49, 0x99,
	0x92, 0x2a, 0xfb, 0xe0, 0xf7, 0xf6, 0x96, 0xf6, 0xe1, 0x6a, 0x1f, 0x5c, 0xfb, 0xd8, 0xd6, 0x3e,
	0xdc, 0x9a, 0x0f, 0x5e, 0xf5, 0xb1, 0xa3, 0x7d, 0xb8, 0x4f, 0xf8, 0xe0, 0xb9, 0x8f, 0x5d, 0xed,
	0xc3, 0x95, 0x3e, 0x86, 0x19, 0x58, 0xc5, 0x04, 0xe8, 0x21, 0x3b, 0xa9, 0x0c, 0xd9, 0x7e, 0x3e,
	0x64, 0x75, 0xac, 0x34, 0x63, 0xc5, 0xe8, 0x34, 0x9e, 0x1b, 0x9d, 0xf5, 0xda, 0xe8, 0x1c, 0xbd,
	0x87, 0x9d, 0x27, 0x87, 0x96, 0x0c, 0xa0, 0x3b, 0x99, 0x8e, 0x2f, 0xbd, 0xb9, 0x7b, 0xe1, 0xce,
	0xbd, 0xe9, 0x47, 0x6b, 0x8d, 0x10, 0xe8, 0xc9, 0xd2, 0x64, 0xea, 0x7a, 0x57, 0xd3, 0xeb, 0xc9,
	0xd8, 0x32, 0x8e, 0xde, 0xc1, 0xf6, 0x53, 0x7e, 0x88, 0x05, 0x9b, 0xb3, 0xe9, 0xb8, 0xdc, 0x3d,
	0x80, 0xae, 0xa8, 0x94, 0x9a, 0xcf, 0xfe, 0x18, 0xd0, 0x9d, 0xe5, 0xcf, 0xbb, 0x9a, 0xfd, 0x31,
	0x58, 0x0e, 0xfa, 0x18, 0xdc, 0xe1, 0xea, 0x5d, 0xb7, 0xea, 0x8f, 0xcb, 0x9e, 0xfd, 0xdc, 0x73,
	0x33, 0x5c, 0x1b, 0x19, 0xa7, 0x06, 0xb9, 0x80, 0x7e, 0xae, 0xa2, 0x1f, 0x95, 0x7e, 0xed, 0xf2,
	0xf6, 0xfe, 0x7f, 0xe6, 0x36, 0x95, 0xc4, 0x4d, 0x4b, 0xfe, 0xd1, 0x9c, 0xff, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x45, 0xd8, 0x0e, 0x23, 0x7f, 0x06, 0x00, 0x00,
}
