// Code generated by protoc-gen-go.
// source: poseidonstats.proto
// DO NOT EDIT!

/*
Package stats is a generated protocol buffer package.

It is generated from these files:
	poseidonstats.proto

It has these top-level messages:
	NodeStats
	NodeStatsResponse
	PodStats
	PodStatsResponse
*/
package stats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeStatsResponseType int32

const (
	NodeStatsResponseType_NODE_STATS_OK  NodeStatsResponseType = 0
	NodeStatsResponseType_NODE_NOT_FOUND NodeStatsResponseType = 1
)

var NodeStatsResponseType_name = map[int32]string{
	0: "NODE_STATS_OK",
	1: "NODE_NOT_FOUND",
}
var NodeStatsResponseType_value = map[string]int32{
	"NODE_STATS_OK":  0,
	"NODE_NOT_FOUND": 1,
}

func (x NodeStatsResponseType) String() string {
	return proto.EnumName(NodeStatsResponseType_name, int32(x))
}
func (NodeStatsResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PodStatsResponseType int32

const (
	PodStatsResponseType_POD_STATS_OK  PodStatsResponseType = 0
	PodStatsResponseType_POD_NOT_FOUND PodStatsResponseType = 1
)

var PodStatsResponseType_name = map[int32]string{
	0: "POD_STATS_OK",
	1: "POD_NOT_FOUND",
}
var PodStatsResponseType_value = map[string]int32{
	"POD_STATS_OK":  0,
	"POD_NOT_FOUND": 1,
}

func (x PodStatsResponseType) String() string {
	return proto.EnumName(PodStatsResponseType_name, int32(x))
}
func (PodStatsResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NodeStats struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	// CPU stats (fraction of total).
	CpuAllocatable float64 `protobuf:"fixed64,2,opt,name=cpu_allocatable,json=cpuAllocatable" json:"cpu_allocatable,omitempty"`
	CpuCapacity    float64 `protobuf:"fixed64,3,opt,name=cpu_capacity,json=cpuCapacity" json:"cpu_capacity,omitempty"`
	CpuReservation float64 `protobuf:"fixed64,4,opt,name=cpu_reservation,json=cpuReservation" json:"cpu_reservation,omitempty"`
	CpuUtilization float64 `protobuf:"fixed64,5,opt,name=cpu_utilization,json=cpuUtilization" json:"cpu_utilization,omitempty"`
	// Memory stats (fraction of total).
	MemAllocatable float64 `protobuf:"fixed64,6,opt,name=mem_allocatable,json=memAllocatable" json:"mem_allocatable,omitempty"`
	MemCapacity    float64 `protobuf:"fixed64,7,opt,name=mem_capacity,json=memCapacity" json:"mem_capacity,omitempty"`
	MemReservation float64 `protobuf:"fixed64,8,opt,name=mem_reservation,json=memReservation" json:"mem_reservation,omitempty"`
	MemUtilization float64 `protobuf:"fixed64,9,opt,name=mem_utilization,json=memUtilization" json:"mem_utilization,omitempty"`
}

func (m *NodeStats) Reset()                    { *m = NodeStats{} }
func (m *NodeStats) String() string            { return proto.CompactTextString(m) }
func (*NodeStats) ProtoMessage()               {}
func (*NodeStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeStats) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeStats) GetCpuAllocatable() float64 {
	if m != nil {
		return m.CpuAllocatable
	}
	return 0
}

func (m *NodeStats) GetCpuCapacity() float64 {
	if m != nil {
		return m.CpuCapacity
	}
	return 0
}

func (m *NodeStats) GetCpuReservation() float64 {
	if m != nil {
		return m.CpuReservation
	}
	return 0
}

func (m *NodeStats) GetCpuUtilization() float64 {
	if m != nil {
		return m.CpuUtilization
	}
	return 0
}

func (m *NodeStats) GetMemAllocatable() float64 {
	if m != nil {
		return m.MemAllocatable
	}
	return 0
}

func (m *NodeStats) GetMemCapacity() float64 {
	if m != nil {
		return m.MemCapacity
	}
	return 0
}

func (m *NodeStats) GetMemReservation() float64 {
	if m != nil {
		return m.MemReservation
	}
	return 0
}

func (m *NodeStats) GetMemUtilization() float64 {
	if m != nil {
		return m.MemUtilization
	}
	return 0
}

type NodeStatsResponse struct {
	Type     NodeStatsResponseType `protobuf:"varint,1,opt,name=type,enum=stats.NodeStatsResponseType" json:"type,omitempty"`
	Hostname string                `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *NodeStatsResponse) Reset()                    { *m = NodeStatsResponse{} }
func (m *NodeStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeStatsResponse) ProtoMessage()               {}
func (*NodeStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeStatsResponse) GetType() NodeStatsResponseType {
	if m != nil {
		return m.Type
	}
	return NodeStatsResponseType_NODE_STATS_OK
}

func (m *NodeStatsResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type PodStats struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Hostname  string `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
	// CPU stats in millicores.
	CpuLimit   int64 `protobuf:"varint,4,opt,name=cpu_limit,json=cpuLimit" json:"cpu_limit,omitempty"`
	CpuRequest int64 `protobuf:"varint,5,opt,name=cpu_request,json=cpuRequest" json:"cpu_request,omitempty"`
	CpuUsage   int64 `protobuf:"varint,6,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
	// Memory stats in Kb.
	MemLimit            int64   `protobuf:"varint,7,opt,name=mem_limit,json=memLimit" json:"mem_limit,omitempty"`
	MemRequest          int64   `protobuf:"varint,8,opt,name=mem_request,json=memRequest" json:"mem_request,omitempty"`
	MemUsage            int64   `protobuf:"varint,9,opt,name=mem_usage,json=memUsage" json:"mem_usage,omitempty"`
	MemRss              int64   `protobuf:"varint,10,opt,name=mem_rss,json=memRss" json:"mem_rss,omitempty"`
	MemCache            int64   `protobuf:"varint,11,opt,name=mem_cache,json=memCache" json:"mem_cache,omitempty"`
	MemWorkingSet       int64   `protobuf:"varint,12,opt,name=mem_working_set,json=memWorkingSet" json:"mem_working_set,omitempty"`
	MemPageFaults       int64   `protobuf:"varint,13,opt,name=mem_page_faults,json=memPageFaults" json:"mem_page_faults,omitempty"`
	MemPageFaultsRate   float64 `protobuf:"fixed64,14,opt,name=mem_page_faults_rate,json=memPageFaultsRate" json:"mem_page_faults_rate,omitempty"`
	MajorPageFaults     int64   `protobuf:"varint,15,opt,name=major_page_faults,json=majorPageFaults" json:"major_page_faults,omitempty"`
	MajorPageFaultsRate float64 `protobuf:"fixed64,16,opt,name=major_page_faults_rate,json=majorPageFaultsRate" json:"major_page_faults_rate,omitempty"`
	// Network stats in Kb.
	NetRx           int64   `protobuf:"varint,17,opt,name=net_rx,json=netRx" json:"net_rx,omitempty"`
	NetRxErrors     int64   `protobuf:"varint,18,opt,name=net_rx_errors,json=netRxErrors" json:"net_rx_errors,omitempty"`
	NetRxErrorsRate float64 `protobuf:"fixed64,19,opt,name=net_rx_errors_rate,json=netRxErrorsRate" json:"net_rx_errors_rate,omitempty"`
	NetRxRate       float64 `protobuf:"fixed64,20,opt,name=net_rx_rate,json=netRxRate" json:"net_rx_rate,omitempty"`
	NetTx           int64   `protobuf:"varint,21,opt,name=net_tx,json=netTx" json:"net_tx,omitempty"`
	NetTxErrors     int64   `protobuf:"varint,22,opt,name=net_tx_errors,json=netTxErrors" json:"net_tx_errors,omitempty"`
	NetTxErrorsRate float64 `protobuf:"fixed64,23,opt,name=net_tx_errors_rate,json=netTxErrorsRate" json:"net_tx_errors_rate,omitempty"`
	NetTxRate       float64 `protobuf:"fixed64,24,opt,name=net_tx_rate,json=netTxRate" json:"net_tx_rate,omitempty"`
}

func (m *PodStats) Reset()                    { *m = PodStats{} }
func (m *PodStats) String() string            { return proto.CompactTextString(m) }
func (*PodStats) ProtoMessage()               {}
func (*PodStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PodStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodStats) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodStats) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PodStats) GetCpuLimit() int64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *PodStats) GetCpuRequest() int64 {
	if m != nil {
		return m.CpuRequest
	}
	return 0
}

func (m *PodStats) GetCpuUsage() int64 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *PodStats) GetMemLimit() int64 {
	if m != nil {
		return m.MemLimit
	}
	return 0
}

func (m *PodStats) GetMemRequest() int64 {
	if m != nil {
		return m.MemRequest
	}
	return 0
}

func (m *PodStats) GetMemUsage() int64 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *PodStats) GetMemRss() int64 {
	if m != nil {
		return m.MemRss
	}
	return 0
}

func (m *PodStats) GetMemCache() int64 {
	if m != nil {
		return m.MemCache
	}
	return 0
}

func (m *PodStats) GetMemWorkingSet() int64 {
	if m != nil {
		return m.MemWorkingSet
	}
	return 0
}

func (m *PodStats) GetMemPageFaults() int64 {
	if m != nil {
		return m.MemPageFaults
	}
	return 0
}

func (m *PodStats) GetMemPageFaultsRate() float64 {
	if m != nil {
		return m.MemPageFaultsRate
	}
	return 0
}

func (m *PodStats) GetMajorPageFaults() int64 {
	if m != nil {
		return m.MajorPageFaults
	}
	return 0
}

func (m *PodStats) GetMajorPageFaultsRate() float64 {
	if m != nil {
		return m.MajorPageFaultsRate
	}
	return 0
}

func (m *PodStats) GetNetRx() int64 {
	if m != nil {
		return m.NetRx
	}
	return 0
}

func (m *PodStats) GetNetRxErrors() int64 {
	if m != nil {
		return m.NetRxErrors
	}
	return 0
}

func (m *PodStats) GetNetRxErrorsRate() float64 {
	if m != nil {
		return m.NetRxErrorsRate
	}
	return 0
}

func (m *PodStats) GetNetRxRate() float64 {
	if m != nil {
		return m.NetRxRate
	}
	return 0
}

func (m *PodStats) GetNetTx() int64 {
	if m != nil {
		return m.NetTx
	}
	return 0
}

func (m *PodStats) GetNetTxErrors() int64 {
	if m != nil {
		return m.NetTxErrors
	}
	return 0
}

func (m *PodStats) GetNetTxErrorsRate() float64 {
	if m != nil {
		return m.NetTxErrorsRate
	}
	return 0
}

func (m *PodStats) GetNetTxRate() float64 {
	if m != nil {
		return m.NetTxRate
	}
	return 0
}

type PodStatsResponse struct {
	Type      PodStatsResponseType `protobuf:"varint,1,opt,name=type,enum=stats.PodStatsResponseType" json:"type,omitempty"`
	Name      string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Namespace string               `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *PodStatsResponse) Reset()                    { *m = PodStatsResponse{} }
func (m *PodStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PodStatsResponse) ProtoMessage()               {}
func (*PodStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PodStatsResponse) GetType() PodStatsResponseType {
	if m != nil {
		return m.Type
	}
	return PodStatsResponseType_POD_STATS_OK
}

func (m *PodStatsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodStatsResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeStats)(nil), "stats.NodeStats")
	proto.RegisterType((*NodeStatsResponse)(nil), "stats.NodeStatsResponse")
	proto.RegisterType((*PodStats)(nil), "stats.PodStats")
	proto.RegisterType((*PodStatsResponse)(nil), "stats.PodStatsResponse")
	proto.RegisterEnum("stats.NodeStatsResponseType", NodeStatsResponseType_name, NodeStatsResponseType_value)
	proto.RegisterEnum("stats.PodStatsResponseType", PodStatsResponseType_name, PodStatsResponseType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PoseidonStats service

type PoseidonStatsClient interface {
	ReceiveNodeStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceiveNodeStatsClient, error)
	ReceivePodStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceivePodStatsClient, error)
}

type poseidonStatsClient struct {
	cc *grpc.ClientConn
}

func NewPoseidonStatsClient(cc *grpc.ClientConn) PoseidonStatsClient {
	return &poseidonStatsClient{cc}
}

func (c *poseidonStatsClient) ReceiveNodeStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceiveNodeStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PoseidonStats_serviceDesc.Streams[0], c.cc, "/stats.PoseidonStats/ReceiveNodeStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &poseidonStatsReceiveNodeStatsClient{stream}
	return x, nil
}

type PoseidonStats_ReceiveNodeStatsClient interface {
	Send(*NodeStats) error
	Recv() (*NodeStatsResponse, error)
	grpc.ClientStream
}

type poseidonStatsReceiveNodeStatsClient struct {
	grpc.ClientStream
}

func (x *poseidonStatsReceiveNodeStatsClient) Send(m *NodeStats) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poseidonStatsReceiveNodeStatsClient) Recv() (*NodeStatsResponse, error) {
	m := new(NodeStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *poseidonStatsClient) ReceivePodStats(ctx context.Context, opts ...grpc.CallOption) (PoseidonStats_ReceivePodStatsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PoseidonStats_serviceDesc.Streams[1], c.cc, "/stats.PoseidonStats/ReceivePodStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &poseidonStatsReceivePodStatsClient{stream}
	return x, nil
}

type PoseidonStats_ReceivePodStatsClient interface {
	Send(*PodStats) error
	Recv() (*PodStatsResponse, error)
	grpc.ClientStream
}

type poseidonStatsReceivePodStatsClient struct {
	grpc.ClientStream
}

func (x *poseidonStatsReceivePodStatsClient) Send(m *PodStats) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poseidonStatsReceivePodStatsClient) Recv() (*PodStatsResponse, error) {
	m := new(PodStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PoseidonStats service

type PoseidonStatsServer interface {
	ReceiveNodeStats(PoseidonStats_ReceiveNodeStatsServer) error
	ReceivePodStats(PoseidonStats_ReceivePodStatsServer) error
}

func RegisterPoseidonStatsServer(s *grpc.Server, srv PoseidonStatsServer) {
	s.RegisterService(&_PoseidonStats_serviceDesc, srv)
}

func _PoseidonStats_ReceiveNodeStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoseidonStatsServer).ReceiveNodeStats(&poseidonStatsReceiveNodeStatsServer{stream})
}

type PoseidonStats_ReceiveNodeStatsServer interface {
	Send(*NodeStatsResponse) error
	Recv() (*NodeStats, error)
	grpc.ServerStream
}

type poseidonStatsReceiveNodeStatsServer struct {
	grpc.ServerStream
}

func (x *poseidonStatsReceiveNodeStatsServer) Send(m *NodeStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poseidonStatsReceiveNodeStatsServer) Recv() (*NodeStats, error) {
	m := new(NodeStats)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PoseidonStats_ReceivePodStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoseidonStatsServer).ReceivePodStats(&poseidonStatsReceivePodStatsServer{stream})
}

type PoseidonStats_ReceivePodStatsServer interface {
	Send(*PodStatsResponse) error
	Recv() (*PodStats, error)
	grpc.ServerStream
}

type poseidonStatsReceivePodStatsServer struct {
	grpc.ServerStream
}

func (x *poseidonStatsReceivePodStatsServer) Send(m *PodStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poseidonStatsReceivePodStatsServer) Recv() (*PodStats, error) {
	m := new(PodStats)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PoseidonStats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.PoseidonStats",
	HandlerType: (*PoseidonStatsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveNodeStats",
			Handler:       _PoseidonStats_ReceiveNodeStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceivePodStats",
			Handler:       _PoseidonStats_ReceivePodStats_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "poseidonstats.proto",
}

func init() { proto.RegisterFile("poseidonstats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x95, 0xdf, 0x4e, 0xdb, 0x48,
	0x14, 0xc6, 0x71, 0x02, 0x21, 0x39, 0x21, 0xff, 0x86, 0x7f, 0x16, 0xa0, 0x5d, 0x36, 0x17, 0xbb,
	0x88, 0x95, 0x00, 0xc1, 0x65, 0xa5, 0x4a, 0x88, 0xc0, 0x4d, 0xab, 0x24, 0x72, 0x8c, 0x7a, 0x69,
	0x0d, 0xe6, 0x34, 0xb8, 0x8d, 0x63, 0xd7, 0x33, 0xa6, 0xd0, 0x27, 0xe9, 0x93, 0xf4, 0x85, 0xfa,
	0x22, 0xd5, 0x9c, 0x89, 0x27, 0xb6, 0x81, 0x2b, 0x98, 0x33, 0xbf, 0xf3, 0xcd, 0xa7, 0xf9, 0x72,
	0xc6, 0xb0, 0x19, 0x47, 0x02, 0x83, 0xfb, 0x68, 0x2e, 0x24, 0x97, 0xe2, 0x24, 0x4e, 0x22, 0x19,
	0xb1, 0x35, 0x5a, 0xf4, 0x7f, 0x57, 0xa0, 0x31, 0x8c, 0xee, 0x71, 0xa2, 0x56, 0x6c, 0x0f, 0xea,
	0x0f, 0x91, 0x90, 0x73, 0x1e, 0xa2, 0x6d, 0x1d, 0x5a, 0x47, 0x0d, 0xc7, 0xac, 0xd9, 0x7f, 0xd0,
	0xf1, 0xe3, 0xd4, 0xe3, 0xb3, 0x59, 0xe4, 0x73, 0xc9, 0xef, 0x66, 0x68, 0x57, 0x0e, 0xad, 0x23,
	0xcb, 0x69, 0xfb, 0x71, 0x7a, 0xb9, 0xac, 0xb2, 0x7f, 0x60, 0x43, 0x81, 0x3e, 0x8f, 0xb9, 0x1f,
	0xc8, 0x67, 0xbb, 0x4a, 0x54, 0xd3, 0x8f, 0xd3, 0xab, 0x45, 0x29, 0xd3, 0x4a, 0x50, 0x60, 0xf2,
	0xc8, 0x65, 0x10, 0xcd, 0xed, 0x55, 0xa3, 0xe5, 0x2c, 0xab, 0x19, 0x98, 0xca, 0x60, 0x16, 0xfc,
	0xd0, 0xe0, 0x9a, 0x01, 0x6f, 0x97, 0x55, 0x05, 0x86, 0x18, 0x16, 0xdc, 0xd5, 0x34, 0x18, 0x62,
	0x58, 0x72, 0xa7, 0x40, 0xe3, 0x6e, 0x5d, 0xbb, 0x0b, 0x31, 0xcc, 0xbb, 0x53, 0x48, 0xde, 0x5d,
	0xdd, 0x68, 0x95, 0xdc, 0x29, 0x30, 0xef, 0xae, 0x61, 0xc0, 0x9c, 0xbb, 0x3e, 0x87, 0x9e, 0xb9,
	0x64, 0x07, 0x45, 0x1c, 0xcd, 0x05, 0xb2, 0x33, 0x58, 0x95, 0xcf, 0xb1, 0xbe, 0xe8, 0xf6, 0xf9,
	0xc1, 0x89, 0x4e, 0xe7, 0x05, 0xe7, 0x3e, 0xc7, 0xe8, 0x10, 0x59, 0x88, 0xa7, 0x52, 0x8c, 0xa7,
	0xff, 0xab, 0x06, 0xf5, 0x71, 0x74, 0xaf, 0x73, 0x64, 0xb0, 0x9a, 0xcb, 0x90, 0xfe, 0x67, 0x07,
	0xd0, 0x50, 0x7f, 0x45, 0xcc, 0xfd, 0xac, 0x7b, 0x59, 0x28, 0x48, 0x57, 0x4b, 0xc9, 0xef, 0x43,
	0x43, 0x85, 0x30, 0x0b, 0xc2, 0x40, 0x52, 0x4e, 0x55, 0xa7, 0xee, 0xc7, 0xe9, 0x47, 0xb5, 0x66,
	0x7f, 0x43, 0x53, 0x47, 0xf9, 0x2d, 0x45, 0x21, 0x29, 0x9d, 0xaa, 0x03, 0x14, 0x23, 0x55, 0xb2,
	0xee, 0x54, 0xf0, 0xa9, 0xce, 0x44, 0x77, 0xdf, 0xaa, 0xb5, 0xda, 0x54, 0x37, 0xa8, 0xa5, 0xd7,
	0xf5, 0x66, 0x88, 0xa1, 0x91, 0xd6, 0x39, 0x68, 0xe9, 0xba, 0x96, 0xa6, 0x0c, 0x8c, 0x34, 0xdd,
	0x3f, 0x49, 0x37, 0x4c, 0xb7, 0x96, 0xde, 0x85, 0x75, 0xea, 0x16, 0xc2, 0x06, 0xda, 0xaa, 0xa9,
	0x4e, 0x21, 0xb2, 0x2e, 0x9f, 0xfb, 0x0f, 0x68, 0x37, 0x4d, 0xd7, 0x95, 0x5a, 0xb3, 0x7f, 0x75,
	0xa4, 0xdf, 0xa3, 0xe4, 0x6b, 0x30, 0x9f, 0x7a, 0x02, 0xa5, 0xbd, 0x41, 0x48, 0x2b, 0xc4, 0xf0,
	0x93, 0xae, 0x4e, 0x50, 0x66, 0x5c, 0xcc, 0xa7, 0xe8, 0x7d, 0xe6, 0xe9, 0x4c, 0x0a, 0xbb, 0x65,
	0xb8, 0x31, 0x9f, 0xe2, 0x0d, 0x15, 0xd9, 0x29, 0x6c, 0x95, 0x38, 0x2f, 0xe1, 0x12, 0xed, 0x36,
	0xfd, 0x4e, 0x7a, 0x05, 0xd8, 0xe1, 0x12, 0xd9, 0x31, 0xf4, 0x42, 0xfe, 0x25, 0x4a, 0x0a, 0xd2,
	0x1d, 0x92, 0xee, 0xd0, 0x46, 0x4e, 0xfc, 0x02, 0x76, 0x5e, 0xb0, 0x5a, 0xbe, 0x4b, 0xf2, 0x9b,
	0xa5, 0x06, 0x3a, 0x60, 0x1b, 0x6a, 0x73, 0x94, 0x5e, 0xf2, 0x64, 0xf7, 0x48, 0x75, 0x6d, 0x8e,
	0xd2, 0x79, 0x62, 0x7d, 0x68, 0xe9, 0xb2, 0x87, 0x49, 0x12, 0x25, 0xc2, 0x66, 0xb4, 0xdb, 0xa4,
	0xdd, 0x6b, 0x2a, 0xb1, 0xff, 0x81, 0x15, 0x18, 0x7d, 0xd6, 0x26, 0x9d, 0xd5, 0xc9, 0x81, 0x74,
	0xce, 0x5f, 0xd0, 0x5c, 0xc0, 0x44, 0x6d, 0x11, 0xd5, 0x20, 0x2a, 0xef, 0x43, 0x3e, 0xd9, 0xdb,
	0xc6, 0x87, 0x6b, 0x7c, 0x48, 0xe3, 0x63, 0xc7, 0xf8, 0x70, 0x4b, 0x3e, 0x64, 0xd1, 0xc7, 0xae,
	0xf1, 0xe1, 0xbe, 0xe2, 0x43, 0x2e, 0x7c, 0xd8, 0xc6, 0x87, 0x4b, 0x3e, 0xfa, 0x29, 0x74, 0xb3,
	0xb9, 0x31, 0xa3, 0x79, 0x5a, 0x18, 0xcd, 0xfd, 0xc5, 0x68, 0x96, 0xb1, 0xdc, 0x64, 0x66, 0x03,
	0x57, 0x79, 0x6b, 0xe0, 0xaa, 0xa5, 0x81, 0x3b, 0x7e, 0x0f, 0xdb, 0xaf, 0x8e, 0x3a, 0xeb, 0x41,
	0x6b, 0x38, 0x1a, 0x5c, 0x7b, 0x13, 0xf7, 0xd2, 0x9d, 0x78, 0xa3, 0x0f, 0xdd, 0x15, 0xc6, 0xa0,
	0x4d, 0xa5, 0xe1, 0xc8, 0xf5, 0x6e, 0x46, 0xb7, 0xc3, 0x41, 0xd7, 0x3a, 0x7e, 0x07, 0x5b, 0xaf,
	0xf9, 0x61, 0x5d, 0xd8, 0x18, 0x8f, 0x06, 0xf9, 0xee, 0x1e, 0xb4, 0x54, 0x25, 0xd7, 0x7c, 0xfe,
	0xd3, 0x82, 0xd6, 0x78, 0xf1, 0x51, 0xd0, 0x2f, 0xc6, 0x00, 0xba, 0x0e, 0xfa, 0x18, 0x3c, 0xe2,
	0xf2, 0x6b, 0xd0, 0x2d, 0x3f, 0x49, 0x7b, 0xf6, 0x5b, 0x8f, 0x54, 0x7f, 0xe5, 0xc8, 0x3a, 0xb3,
	0xd8, 0x25, 0x74, 0x16, 0x2a, 0xe6, 0x29, 0xea, 0x94, 0x2e, 0x6f, 0x6f, 0xf7, 0x8d, 0xdb, 0xd4,
	0x12, 0x77, 0x35, 0xfa, 0x3c, 0x5d, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xca, 0xff, 0x8e,
	0xb5, 0x06, 0x00, 0x00,
}
