/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: firmament_scheduler.proto

package firmament

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskReplyType int32

const (
	TaskReplyType_TASK_COMPLETED_OK      TaskReplyType = 0
	TaskReplyType_TASK_SUBMITTED_OK      TaskReplyType = 1
	TaskReplyType_TASK_REMOVED_OK        TaskReplyType = 2
	TaskReplyType_TASK_FAILED_OK         TaskReplyType = 3
	TaskReplyType_TASK_UPDATED_OK        TaskReplyType = 4
	TaskReplyType_TASK_NOT_FOUND         TaskReplyType = 5
	TaskReplyType_TASK_JOB_NOT_FOUND     TaskReplyType = 6
	TaskReplyType_TASK_ALREADY_SUBMITTED TaskReplyType = 7
	TaskReplyType_TASK_STATE_NOT_CREATED TaskReplyType = 8
)

var TaskReplyType_name = map[int32]string{
	0: "TASK_COMPLETED_OK",
	1: "TASK_SUBMITTED_OK",
	2: "TASK_REMOVED_OK",
	3: "TASK_FAILED_OK",
	4: "TASK_UPDATED_OK",
	5: "TASK_NOT_FOUND",
	6: "TASK_JOB_NOT_FOUND",
	7: "TASK_ALREADY_SUBMITTED",
	8: "TASK_STATE_NOT_CREATED",
}
var TaskReplyType_value = map[string]int32{
	"TASK_COMPLETED_OK":      0,
	"TASK_SUBMITTED_OK":      1,
	"TASK_REMOVED_OK":        2,
	"TASK_FAILED_OK":         3,
	"TASK_UPDATED_OK":        4,
	"TASK_NOT_FOUND":         5,
	"TASK_JOB_NOT_FOUND":     6,
	"TASK_ALREADY_SUBMITTED": 7,
	"TASK_STATE_NOT_CREATED": 8,
}

func (x TaskReplyType) String() string {
	return proto.EnumName(TaskReplyType_name, int32(x))
}
func (TaskReplyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{0}
}

type NodeReplyType int32

const (
	NodeReplyType_NODE_ADDED_OK       NodeReplyType = 0
	NodeReplyType_NODE_FAILED_OK      NodeReplyType = 1
	NodeReplyType_NODE_REMOVED_OK     NodeReplyType = 2
	NodeReplyType_NODE_UPDATED_OK     NodeReplyType = 3
	NodeReplyType_NODE_NOT_FOUND      NodeReplyType = 4
	NodeReplyType_NODE_ALREADY_EXISTS NodeReplyType = 5
)

var NodeReplyType_name = map[int32]string{
	0: "NODE_ADDED_OK",
	1: "NODE_FAILED_OK",
	2: "NODE_REMOVED_OK",
	3: "NODE_UPDATED_OK",
	4: "NODE_NOT_FOUND",
	5: "NODE_ALREADY_EXISTS",
}
var NodeReplyType_value = map[string]int32{
	"NODE_ADDED_OK":       0,
	"NODE_FAILED_OK":      1,
	"NODE_REMOVED_OK":     2,
	"NODE_UPDATED_OK":     3,
	"NODE_NOT_FOUND":      4,
	"NODE_ALREADY_EXISTS": 5,
}

func (x NodeReplyType) String() string {
	return proto.EnumName(NodeReplyType_name, int32(x))
}
func (NodeReplyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{1}
}

type ServingStatus int32

const (
	ServingStatus_UNKNOWN     ServingStatus = 0
	ServingStatus_SERVING     ServingStatus = 1
	ServingStatus_NOT_SERVING ServingStatus = 2
)

var ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}
var ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x ServingStatus) String() string {
	return proto.EnumName(ServingStatus_name, int32(x))
}
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{2}
}

type TaskInfoReplyType int32

const (
	TaskInfoReplyType_TASKINFO_SUBMITTED_OK  TaskInfoReplyType = 0
	TaskInfoReplyType_TASKINFO_REMOVED_OK    TaskInfoReplyType = 2
	TaskInfoReplyType_TASKINFO_SUBMIT_FAILED TaskInfoReplyType = 3
	TaskInfoReplyType_TASKINFO_REMOVE_FAILED TaskInfoReplyType = 4
)

var TaskInfoReplyType_name = map[int32]string{
	0: "TASKINFO_SUBMITTED_OK",
	2: "TASKINFO_REMOVED_OK",
	3: "TASKINFO_SUBMIT_FAILED",
	4: "TASKINFO_REMOVE_FAILED",
}
var TaskInfoReplyType_value = map[string]int32{
	"TASKINFO_SUBMITTED_OK":  0,
	"TASKINFO_REMOVED_OK":    2,
	"TASKINFO_SUBMIT_FAILED": 3,
	"TASKINFO_REMOVE_FAILED": 4,
}

func (x TaskInfoReplyType) String() string {
	return proto.EnumName(TaskInfoReplyType_name, int32(x))
}
func (TaskInfoReplyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{3}
}

type TaskInfoType int32

const (
	TaskInfoType_TASKINFO_ADD    TaskInfoType = 0
	TaskInfoType_TASKINFO_REMOVE TaskInfoType = 1
)

var TaskInfoType_name = map[int32]string{
	0: "TASKINFO_ADD",
	1: "TASKINFO_REMOVE",
}
var TaskInfoType_value = map[string]int32{
	"TASKINFO_ADD":    0,
	"TASKINFO_REMOVE": 1,
}

func (x TaskInfoType) String() string {
	return proto.EnumName(TaskInfoType_name, int32(x))
}
func (TaskInfoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{4}
}

type ScheduleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleRequest) Reset()         { *m = ScheduleRequest{} }
func (m *ScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*ScheduleRequest) ProtoMessage()    {}
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{0}
}
func (m *ScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleRequest.Unmarshal(m, b)
}
func (m *ScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleRequest.Marshal(b, m, deterministic)
}
func (dst *ScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleRequest.Merge(dst, src)
}
func (m *ScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_ScheduleRequest.Size(m)
}
func (m *ScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleRequest proto.InternalMessageInfo

type SchedulingDeltas struct {
	Deltas               []*SchedulingDelta `protobuf:"bytes,1,rep,name=deltas,proto3" json:"deltas,omitempty"`
	UnscheduledTasks     []uint64           `protobuf:"varint,2,rep,packed,name=unscheduled_tasks,json=unscheduledTasks,proto3" json:"unscheduled_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SchedulingDeltas) Reset()         { *m = SchedulingDeltas{} }
func (m *SchedulingDeltas) String() string { return proto.CompactTextString(m) }
func (*SchedulingDeltas) ProtoMessage()    {}
func (*SchedulingDeltas) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{1}
}
func (m *SchedulingDeltas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingDeltas.Unmarshal(m, b)
}
func (m *SchedulingDeltas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingDeltas.Marshal(b, m, deterministic)
}
func (dst *SchedulingDeltas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingDeltas.Merge(dst, src)
}
func (m *SchedulingDeltas) XXX_Size() int {
	return xxx_messageInfo_SchedulingDeltas.Size(m)
}
func (m *SchedulingDeltas) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingDeltas.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingDeltas proto.InternalMessageInfo

func (m *SchedulingDeltas) GetDeltas() []*SchedulingDelta {
	if m != nil {
		return m.Deltas
	}
	return nil
}

func (m *SchedulingDeltas) GetUnscheduledTasks() []uint64 {
	if m != nil {
		return m.UnscheduledTasks
	}
	return nil
}

type TaskCompletedResponse struct {
	Type                 TaskReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskCompletedResponse) Reset()         { *m = TaskCompletedResponse{} }
func (m *TaskCompletedResponse) String() string { return proto.CompactTextString(m) }
func (*TaskCompletedResponse) ProtoMessage()    {}
func (*TaskCompletedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{2}
}
func (m *TaskCompletedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskCompletedResponse.Unmarshal(m, b)
}
func (m *TaskCompletedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskCompletedResponse.Marshal(b, m, deterministic)
}
func (dst *TaskCompletedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskCompletedResponse.Merge(dst, src)
}
func (m *TaskCompletedResponse) XXX_Size() int {
	return xxx_messageInfo_TaskCompletedResponse.Size(m)
}
func (m *TaskCompletedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskCompletedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskCompletedResponse proto.InternalMessageInfo

func (m *TaskCompletedResponse) GetType() TaskReplyType {
	if m != nil {
		return m.Type
	}
	return TaskReplyType_TASK_COMPLETED_OK
}

type TaskDescription struct {
	TaskDescriptor       *TaskDescriptor `protobuf:"bytes,1,opt,name=task_descriptor,json=taskDescriptor,proto3" json:"task_descriptor,omitempty"`
	JobDescriptor        *JobDescriptor  `protobuf:"bytes,2,opt,name=job_descriptor,json=jobDescriptor,proto3" json:"job_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TaskDescription) Reset()         { *m = TaskDescription{} }
func (m *TaskDescription) String() string { return proto.CompactTextString(m) }
func (*TaskDescription) ProtoMessage()    {}
func (*TaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{3}
}
func (m *TaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescription.Unmarshal(m, b)
}
func (m *TaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescription.Marshal(b, m, deterministic)
}
func (dst *TaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescription.Merge(dst, src)
}
func (m *TaskDescription) XXX_Size() int {
	return xxx_messageInfo_TaskDescription.Size(m)
}
func (m *TaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescription proto.InternalMessageInfo

func (m *TaskDescription) GetTaskDescriptor() *TaskDescriptor {
	if m != nil {
		return m.TaskDescriptor
	}
	return nil
}

func (m *TaskDescription) GetJobDescriptor() *JobDescriptor {
	if m != nil {
		return m.JobDescriptor
	}
	return nil
}

type TaskSubmittedResponse struct {
	Type                 TaskReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskSubmittedResponse) Reset()         { *m = TaskSubmittedResponse{} }
func (m *TaskSubmittedResponse) String() string { return proto.CompactTextString(m) }
func (*TaskSubmittedResponse) ProtoMessage()    {}
func (*TaskSubmittedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{4}
}
func (m *TaskSubmittedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskSubmittedResponse.Unmarshal(m, b)
}
func (m *TaskSubmittedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskSubmittedResponse.Marshal(b, m, deterministic)
}
func (dst *TaskSubmittedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskSubmittedResponse.Merge(dst, src)
}
func (m *TaskSubmittedResponse) XXX_Size() int {
	return xxx_messageInfo_TaskSubmittedResponse.Size(m)
}
func (m *TaskSubmittedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskSubmittedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskSubmittedResponse proto.InternalMessageInfo

func (m *TaskSubmittedResponse) GetType() TaskReplyType {
	if m != nil {
		return m.Type
	}
	return TaskReplyType_TASK_COMPLETED_OK
}

type TaskRemovedResponse struct {
	Type                 TaskReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskRemovedResponse) Reset()         { *m = TaskRemovedResponse{} }
func (m *TaskRemovedResponse) String() string { return proto.CompactTextString(m) }
func (*TaskRemovedResponse) ProtoMessage()    {}
func (*TaskRemovedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{5}
}
func (m *TaskRemovedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRemovedResponse.Unmarshal(m, b)
}
func (m *TaskRemovedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRemovedResponse.Marshal(b, m, deterministic)
}
func (dst *TaskRemovedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRemovedResponse.Merge(dst, src)
}
func (m *TaskRemovedResponse) XXX_Size() int {
	return xxx_messageInfo_TaskRemovedResponse.Size(m)
}
func (m *TaskRemovedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRemovedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRemovedResponse proto.InternalMessageInfo

func (m *TaskRemovedResponse) GetType() TaskReplyType {
	if m != nil {
		return m.Type
	}
	return TaskReplyType_TASK_COMPLETED_OK
}

type TaskFailedResponse struct {
	Type                 TaskReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskFailedResponse) Reset()         { *m = TaskFailedResponse{} }
func (m *TaskFailedResponse) String() string { return proto.CompactTextString(m) }
func (*TaskFailedResponse) ProtoMessage()    {}
func (*TaskFailedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{6}
}
func (m *TaskFailedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskFailedResponse.Unmarshal(m, b)
}
func (m *TaskFailedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskFailedResponse.Marshal(b, m, deterministic)
}
func (dst *TaskFailedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskFailedResponse.Merge(dst, src)
}
func (m *TaskFailedResponse) XXX_Size() int {
	return xxx_messageInfo_TaskFailedResponse.Size(m)
}
func (m *TaskFailedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskFailedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskFailedResponse proto.InternalMessageInfo

func (m *TaskFailedResponse) GetType() TaskReplyType {
	if m != nil {
		return m.Type
	}
	return TaskReplyType_TASK_COMPLETED_OK
}

type TaskUpdatedResponse struct {
	Type                 TaskReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskUpdatedResponse) Reset()         { *m = TaskUpdatedResponse{} }
func (m *TaskUpdatedResponse) String() string { return proto.CompactTextString(m) }
func (*TaskUpdatedResponse) ProtoMessage()    {}
func (*TaskUpdatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{7}
}
func (m *TaskUpdatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUpdatedResponse.Unmarshal(m, b)
}
func (m *TaskUpdatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUpdatedResponse.Marshal(b, m, deterministic)
}
func (dst *TaskUpdatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUpdatedResponse.Merge(dst, src)
}
func (m *TaskUpdatedResponse) XXX_Size() int {
	return xxx_messageInfo_TaskUpdatedResponse.Size(m)
}
func (m *TaskUpdatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUpdatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUpdatedResponse proto.InternalMessageInfo

func (m *TaskUpdatedResponse) GetType() TaskReplyType {
	if m != nil {
		return m.Type
	}
	return TaskReplyType_TASK_COMPLETED_OK
}

type NodeAddedResponse struct {
	Type                 NodeReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.NodeReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeAddedResponse) Reset()         { *m = NodeAddedResponse{} }
func (m *NodeAddedResponse) String() string { return proto.CompactTextString(m) }
func (*NodeAddedResponse) ProtoMessage()    {}
func (*NodeAddedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{8}
}
func (m *NodeAddedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddedResponse.Unmarshal(m, b)
}
func (m *NodeAddedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddedResponse.Marshal(b, m, deterministic)
}
func (dst *NodeAddedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddedResponse.Merge(dst, src)
}
func (m *NodeAddedResponse) XXX_Size() int {
	return xxx_messageInfo_NodeAddedResponse.Size(m)
}
func (m *NodeAddedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddedResponse proto.InternalMessageInfo

func (m *NodeAddedResponse) GetType() NodeReplyType {
	if m != nil {
		return m.Type
	}
	return NodeReplyType_NODE_ADDED_OK
}

type NodeRemovedResponse struct {
	Type                 NodeReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.NodeReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeRemovedResponse) Reset()         { *m = NodeRemovedResponse{} }
func (m *NodeRemovedResponse) String() string { return proto.CompactTextString(m) }
func (*NodeRemovedResponse) ProtoMessage()    {}
func (*NodeRemovedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{9}
}
func (m *NodeRemovedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRemovedResponse.Unmarshal(m, b)
}
func (m *NodeRemovedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRemovedResponse.Marshal(b, m, deterministic)
}
func (dst *NodeRemovedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRemovedResponse.Merge(dst, src)
}
func (m *NodeRemovedResponse) XXX_Size() int {
	return xxx_messageInfo_NodeRemovedResponse.Size(m)
}
func (m *NodeRemovedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRemovedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRemovedResponse proto.InternalMessageInfo

func (m *NodeRemovedResponse) GetType() NodeReplyType {
	if m != nil {
		return m.Type
	}
	return NodeReplyType_NODE_ADDED_OK
}

type NodeFailedResponse struct {
	Type                 NodeReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.NodeReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeFailedResponse) Reset()         { *m = NodeFailedResponse{} }
func (m *NodeFailedResponse) String() string { return proto.CompactTextString(m) }
func (*NodeFailedResponse) ProtoMessage()    {}
func (*NodeFailedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{10}
}
func (m *NodeFailedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeFailedResponse.Unmarshal(m, b)
}
func (m *NodeFailedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeFailedResponse.Marshal(b, m, deterministic)
}
func (dst *NodeFailedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeFailedResponse.Merge(dst, src)
}
func (m *NodeFailedResponse) XXX_Size() int {
	return xxx_messageInfo_NodeFailedResponse.Size(m)
}
func (m *NodeFailedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeFailedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeFailedResponse proto.InternalMessageInfo

func (m *NodeFailedResponse) GetType() NodeReplyType {
	if m != nil {
		return m.Type
	}
	return NodeReplyType_NODE_ADDED_OK
}

type NodeUpdatedResponse struct {
	Type                 NodeReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.NodeReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeUpdatedResponse) Reset()         { *m = NodeUpdatedResponse{} }
func (m *NodeUpdatedResponse) String() string { return proto.CompactTextString(m) }
func (*NodeUpdatedResponse) ProtoMessage()    {}
func (*NodeUpdatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{11}
}
func (m *NodeUpdatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeUpdatedResponse.Unmarshal(m, b)
}
func (m *NodeUpdatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeUpdatedResponse.Marshal(b, m, deterministic)
}
func (dst *NodeUpdatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeUpdatedResponse.Merge(dst, src)
}
func (m *NodeUpdatedResponse) XXX_Size() int {
	return xxx_messageInfo_NodeUpdatedResponse.Size(m)
}
func (m *NodeUpdatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeUpdatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeUpdatedResponse proto.InternalMessageInfo

func (m *NodeUpdatedResponse) GetType() NodeReplyType {
	if m != nil {
		return m.Type
	}
	return NodeReplyType_NODE_ADDED_OK
}

type TaskStatsResponse struct {
	Type                 TaskReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskStatsResponse) Reset()         { *m = TaskStatsResponse{} }
func (m *TaskStatsResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStatsResponse) ProtoMessage()    {}
func (*TaskStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{12}
}
func (m *TaskStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatsResponse.Unmarshal(m, b)
}
func (m *TaskStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatsResponse.Marshal(b, m, deterministic)
}
func (dst *TaskStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatsResponse.Merge(dst, src)
}
func (m *TaskStatsResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStatsResponse.Size(m)
}
func (m *TaskStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatsResponse proto.InternalMessageInfo

func (m *TaskStatsResponse) GetType() TaskReplyType {
	if m != nil {
		return m.Type
	}
	return TaskReplyType_TASK_COMPLETED_OK
}

type ResourceStatsResponse struct {
	Type                 NodeReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.NodeReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResourceStatsResponse) Reset()         { *m = ResourceStatsResponse{} }
func (m *ResourceStatsResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceStatsResponse) ProtoMessage()    {}
func (*ResourceStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{13}
}
func (m *ResourceStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceStatsResponse.Unmarshal(m, b)
}
func (m *ResourceStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceStatsResponse.Marshal(b, m, deterministic)
}
func (dst *ResourceStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceStatsResponse.Merge(dst, src)
}
func (m *ResourceStatsResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceStatsResponse.Size(m)
}
func (m *ResourceStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceStatsResponse proto.InternalMessageInfo

func (m *ResourceStatsResponse) GetType() NodeReplyType {
	if m != nil {
		return m.Type
	}
	return NodeReplyType_NODE_ADDED_OK
}

type TaskUID struct {
	TaskUid              uint64   `protobuf:"varint,1,opt,name=task_uid,json=taskUid,proto3" json:"task_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskUID) Reset()         { *m = TaskUID{} }
func (m *TaskUID) String() string { return proto.CompactTextString(m) }
func (*TaskUID) ProtoMessage()    {}
func (*TaskUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{14}
}
func (m *TaskUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUID.Unmarshal(m, b)
}
func (m *TaskUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUID.Marshal(b, m, deterministic)
}
func (dst *TaskUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUID.Merge(dst, src)
}
func (m *TaskUID) XXX_Size() int {
	return xxx_messageInfo_TaskUID.Size(m)
}
func (m *TaskUID) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUID.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUID proto.InternalMessageInfo

func (m *TaskUID) GetTaskUid() uint64 {
	if m != nil {
		return m.TaskUid
	}
	return 0
}

type ResourceUID struct {
	ResourceUid          string   `protobuf:"bytes,1,opt,name=resource_uid,json=resourceUid,proto3" json:"resource_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceUID) Reset()         { *m = ResourceUID{} }
func (m *ResourceUID) String() string { return proto.CompactTextString(m) }
func (*ResourceUID) ProtoMessage()    {}
func (*ResourceUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{15}
}
func (m *ResourceUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceUID.Unmarshal(m, b)
}
func (m *ResourceUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceUID.Marshal(b, m, deterministic)
}
func (dst *ResourceUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUID.Merge(dst, src)
}
func (m *ResourceUID) XXX_Size() int {
	return xxx_messageInfo_ResourceUID.Size(m)
}
func (m *ResourceUID) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUID.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUID proto.InternalMessageInfo

func (m *ResourceUID) GetResourceUid() string {
	if m != nil {
		return m.ResourceUid
	}
	return ""
}

type HealthCheckRequest struct {
	GrpcService          string   `protobuf:"bytes,1,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{16}
}
func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (dst *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(dst, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetGrpcService() string {
	if m != nil {
		return m.GrpcService
	}
	return ""
}

type HealthCheckResponse struct {
	Status               ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=firmament.ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{17}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (dst *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(dst, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() ServingStatus {
	if m != nil {
		return m.Status
	}
	return ServingStatus_UNKNOWN
}

// TaskInfo is the stats(including CPU, Memory and ephemeral) of a task.
type TaskInfo struct {
	TaskName                    string       `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	ResourceId                  string       `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	CpuUtilization              int64        `protobuf:"varint,3,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	MemUtilization              int64        `protobuf:"varint,4,opt,name=mem_utilization,json=memUtilization,proto3" json:"mem_utilization,omitempty"`
	EphemeralStorageUtilization int64        `protobuf:"varint,5,opt,name=ephemeral_storage_utilization,json=ephemeralStorageUtilization,proto3" json:"ephemeral_storage_utilization,omitempty"`
	Type                        TaskInfoType `protobuf:"varint,6,opt,name=type,proto3,enum=firmament.TaskInfoType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}     `json:"-"`
	XXX_unrecognized            []byte       `json:"-"`
	XXX_sizecache               int32        `json:"-"`
}

func (m *TaskInfo) Reset()         { *m = TaskInfo{} }
func (m *TaskInfo) String() string { return proto.CompactTextString(m) }
func (*TaskInfo) ProtoMessage()    {}
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{18}
}
func (m *TaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskInfo.Unmarshal(m, b)
}
func (m *TaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskInfo.Marshal(b, m, deterministic)
}
func (dst *TaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskInfo.Merge(dst, src)
}
func (m *TaskInfo) XXX_Size() int {
	return xxx_messageInfo_TaskInfo.Size(m)
}
func (m *TaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaskInfo proto.InternalMessageInfo

func (m *TaskInfo) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *TaskInfo) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *TaskInfo) GetCpuUtilization() int64 {
	if m != nil {
		return m.CpuUtilization
	}
	return 0
}

func (m *TaskInfo) GetMemUtilization() int64 {
	if m != nil {
		return m.MemUtilization
	}
	return 0
}

func (m *TaskInfo) GetEphemeralStorageUtilization() int64 {
	if m != nil {
		return m.EphemeralStorageUtilization
	}
	return 0
}

func (m *TaskInfo) GetType() TaskInfoType {
	if m != nil {
		return m.Type
	}
	return TaskInfoType_TASKINFO_ADD
}

type TaskInfoResponse struct {
	Type                 TaskInfoReplyType `protobuf:"varint,1,opt,name=type,proto3,enum=firmament.TaskInfoReplyType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TaskInfoResponse) Reset()         { *m = TaskInfoResponse{} }
func (m *TaskInfoResponse) String() string { return proto.CompactTextString(m) }
func (*TaskInfoResponse) ProtoMessage()    {}
func (*TaskInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92, []int{19}
}
func (m *TaskInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskInfoResponse.Unmarshal(m, b)
}
func (m *TaskInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskInfoResponse.Marshal(b, m, deterministic)
}
func (dst *TaskInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskInfoResponse.Merge(dst, src)
}
func (m *TaskInfoResponse) XXX_Size() int {
	return xxx_messageInfo_TaskInfoResponse.Size(m)
}
func (m *TaskInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskInfoResponse proto.InternalMessageInfo

func (m *TaskInfoResponse) GetType() TaskInfoReplyType {
	if m != nil {
		return m.Type
	}
	return TaskInfoReplyType_TASKINFO_SUBMITTED_OK
}

func init() {
	proto.RegisterType((*ScheduleRequest)(nil), "firmament.ScheduleRequest")
	proto.RegisterType((*SchedulingDeltas)(nil), "firmament.SchedulingDeltas")
	proto.RegisterType((*TaskCompletedResponse)(nil), "firmament.TaskCompletedResponse")
	proto.RegisterType((*TaskDescription)(nil), "firmament.TaskDescription")
	proto.RegisterType((*TaskSubmittedResponse)(nil), "firmament.TaskSubmittedResponse")
	proto.RegisterType((*TaskRemovedResponse)(nil), "firmament.TaskRemovedResponse")
	proto.RegisterType((*TaskFailedResponse)(nil), "firmament.TaskFailedResponse")
	proto.RegisterType((*TaskUpdatedResponse)(nil), "firmament.TaskUpdatedResponse")
	proto.RegisterType((*NodeAddedResponse)(nil), "firmament.NodeAddedResponse")
	proto.RegisterType((*NodeRemovedResponse)(nil), "firmament.NodeRemovedResponse")
	proto.RegisterType((*NodeFailedResponse)(nil), "firmament.NodeFailedResponse")
	proto.RegisterType((*NodeUpdatedResponse)(nil), "firmament.NodeUpdatedResponse")
	proto.RegisterType((*TaskStatsResponse)(nil), "firmament.TaskStatsResponse")
	proto.RegisterType((*ResourceStatsResponse)(nil), "firmament.ResourceStatsResponse")
	proto.RegisterType((*TaskUID)(nil), "firmament.TaskUID")
	proto.RegisterType((*ResourceUID)(nil), "firmament.ResourceUID")
	proto.RegisterType((*HealthCheckRequest)(nil), "firmament.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "firmament.HealthCheckResponse")
	proto.RegisterType((*TaskInfo)(nil), "firmament.TaskInfo")
	proto.RegisterType((*TaskInfoResponse)(nil), "firmament.TaskInfoResponse")
	proto.RegisterEnum("firmament.TaskReplyType", TaskReplyType_name, TaskReplyType_value)
	proto.RegisterEnum("firmament.NodeReplyType", NodeReplyType_name, NodeReplyType_value)
	proto.RegisterEnum("firmament.ServingStatus", ServingStatus_name, ServingStatus_value)
	proto.RegisterEnum("firmament.TaskInfoReplyType", TaskInfoReplyType_name, TaskInfoReplyType_value)
	proto.RegisterEnum("firmament.TaskInfoType", TaskInfoType_name, TaskInfoType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FirmamentSchedulerClient is the client API for FirmamentScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FirmamentSchedulerClient interface {
	// Schedule sends a schedule request to firmament server.
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*SchedulingDeltas, error)
	// TaskCompleted notifies firmament server the given task is completed.
	TaskCompleted(ctx context.Context, in *TaskUID, opts ...grpc.CallOption) (*TaskCompletedResponse, error)
	// TaskFailed notifies firmament server the given task is failed.
	TaskFailed(ctx context.Context, in *TaskUID, opts ...grpc.CallOption) (*TaskFailedResponse, error)
	// TaskRemoved notifies firmament server the given task is removed.
	TaskRemoved(ctx context.Context, in *TaskUID, opts ...grpc.CallOption) (*TaskRemovedResponse, error)
	// TaskSubmitted notifies firmament server the given task is submitted.
	TaskSubmitted(ctx context.Context, in *TaskDescription, opts ...grpc.CallOption) (*TaskSubmittedResponse, error)
	// TaskUpdated notifies firmament server the given task is updated.
	TaskUpdated(ctx context.Context, in *TaskDescription, opts ...grpc.CallOption) (*TaskUpdatedResponse, error)
	// NodeAdded notifies firmament server the given node is added.
	NodeAdded(ctx context.Context, in *ResourceTopologyNodeDescriptor, opts ...grpc.CallOption) (*NodeAddedResponse, error)
	// NodeFailed notifies firmament server the given node is failed.
	NodeFailed(ctx context.Context, in *ResourceUID, opts ...grpc.CallOption) (*NodeFailedResponse, error)
	// NodeRemoved notifies firmament server the given node is removed.
	NodeRemoved(ctx context.Context, in *ResourceUID, opts ...grpc.CallOption) (*NodeRemovedResponse, error)
	// NodeUpdated notifies firmament server the given node is updated.
	NodeUpdated(ctx context.Context, in *ResourceTopologyNodeDescriptor, opts ...grpc.CallOption) (*NodeUpdatedResponse, error)
	// AddTaskStats sends task status to firmament server.
	AddTaskStats(ctx context.Context, in *TaskStats, opts ...grpc.CallOption) (*TaskStatsResponse, error)
	// AddNodeStats sends node status to firmament server.
	AddNodeStats(ctx context.Context, in *ResourceStats, opts ...grpc.CallOption) (*ResourceStatsResponse, error)
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// AddTaskInfo sends task status to firmament server.
	AddTaskInfo(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*TaskInfoResponse, error)
}

type firmamentSchedulerClient struct {
	cc *grpc.ClientConn
}

func NewFirmamentSchedulerClient(cc *grpc.ClientConn) FirmamentSchedulerClient {
	return &firmamentSchedulerClient{cc}
}

func (c *firmamentSchedulerClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*SchedulingDeltas, error) {
	out := new(SchedulingDeltas)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/Schedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) TaskCompleted(ctx context.Context, in *TaskUID, opts ...grpc.CallOption) (*TaskCompletedResponse, error) {
	out := new(TaskCompletedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/TaskCompleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) TaskFailed(ctx context.Context, in *TaskUID, opts ...grpc.CallOption) (*TaskFailedResponse, error) {
	out := new(TaskFailedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/TaskFailed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) TaskRemoved(ctx context.Context, in *TaskUID, opts ...grpc.CallOption) (*TaskRemovedResponse, error) {
	out := new(TaskRemovedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/TaskRemoved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) TaskSubmitted(ctx context.Context, in *TaskDescription, opts ...grpc.CallOption) (*TaskSubmittedResponse, error) {
	out := new(TaskSubmittedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/TaskSubmitted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) TaskUpdated(ctx context.Context, in *TaskDescription, opts ...grpc.CallOption) (*TaskUpdatedResponse, error) {
	out := new(TaskUpdatedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/TaskUpdated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) NodeAdded(ctx context.Context, in *ResourceTopologyNodeDescriptor, opts ...grpc.CallOption) (*NodeAddedResponse, error) {
	out := new(NodeAddedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/NodeAdded", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) NodeFailed(ctx context.Context, in *ResourceUID, opts ...grpc.CallOption) (*NodeFailedResponse, error) {
	out := new(NodeFailedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/NodeFailed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) NodeRemoved(ctx context.Context, in *ResourceUID, opts ...grpc.CallOption) (*NodeRemovedResponse, error) {
	out := new(NodeRemovedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/NodeRemoved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) NodeUpdated(ctx context.Context, in *ResourceTopologyNodeDescriptor, opts ...grpc.CallOption) (*NodeUpdatedResponse, error) {
	out := new(NodeUpdatedResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/NodeUpdated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) AddTaskStats(ctx context.Context, in *TaskStats, opts ...grpc.CallOption) (*TaskStatsResponse, error) {
	out := new(TaskStatsResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/AddTaskStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) AddNodeStats(ctx context.Context, in *ResourceStats, opts ...grpc.CallOption) (*ResourceStatsResponse, error) {
	out := new(ResourceStatsResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/AddNodeStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmamentSchedulerClient) AddTaskInfo(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*TaskInfoResponse, error) {
	out := new(TaskInfoResponse)
	err := c.cc.Invoke(ctx, "/firmament.FirmamentScheduler/AddTaskInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirmamentSchedulerServer is the server API for FirmamentScheduler service.
type FirmamentSchedulerServer interface {
	// Schedule sends a schedule request to firmament server.
	Schedule(context.Context, *ScheduleRequest) (*SchedulingDeltas, error)
	// TaskCompleted notifies firmament server the given task is completed.
	TaskCompleted(context.Context, *TaskUID) (*TaskCompletedResponse, error)
	// TaskFailed notifies firmament server the given task is failed.
	TaskFailed(context.Context, *TaskUID) (*TaskFailedResponse, error)
	// TaskRemoved notifies firmament server the given task is removed.
	TaskRemoved(context.Context, *TaskUID) (*TaskRemovedResponse, error)
	// TaskSubmitted notifies firmament server the given task is submitted.
	TaskSubmitted(context.Context, *TaskDescription) (*TaskSubmittedResponse, error)
	// TaskUpdated notifies firmament server the given task is updated.
	TaskUpdated(context.Context, *TaskDescription) (*TaskUpdatedResponse, error)
	// NodeAdded notifies firmament server the given node is added.
	NodeAdded(context.Context, *ResourceTopologyNodeDescriptor) (*NodeAddedResponse, error)
	// NodeFailed notifies firmament server the given node is failed.
	NodeFailed(context.Context, *ResourceUID) (*NodeFailedResponse, error)
	// NodeRemoved notifies firmament server the given node is removed.
	NodeRemoved(context.Context, *ResourceUID) (*NodeRemovedResponse, error)
	// NodeUpdated notifies firmament server the given node is updated.
	NodeUpdated(context.Context, *ResourceTopologyNodeDescriptor) (*NodeUpdatedResponse, error)
	// AddTaskStats sends task status to firmament server.
	AddTaskStats(context.Context, *TaskStats) (*TaskStatsResponse, error)
	// AddNodeStats sends node status to firmament server.
	AddNodeStats(context.Context, *ResourceStats) (*ResourceStatsResponse, error)
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// AddTaskInfo sends task status to firmament server.
	AddTaskInfo(context.Context, *TaskInfo) (*TaskInfoResponse, error)
}

func RegisterFirmamentSchedulerServer(s *grpc.Server, srv FirmamentSchedulerServer) {
	s.RegisterService(&_FirmamentScheduler_serviceDesc, srv)
}

func _FirmamentScheduler_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/Schedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_TaskCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).TaskCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/TaskCompleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).TaskCompleted(ctx, req.(*TaskUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_TaskFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).TaskFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/TaskFailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).TaskFailed(ctx, req.(*TaskUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_TaskRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).TaskRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/TaskRemoved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).TaskRemoved(ctx, req.(*TaskUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_TaskSubmitted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).TaskSubmitted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/TaskSubmitted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).TaskSubmitted(ctx, req.(*TaskDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_TaskUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).TaskUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/TaskUpdated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).TaskUpdated(ctx, req.(*TaskDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_NodeAdded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceTopologyNodeDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).NodeAdded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/NodeAdded",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).NodeAdded(ctx, req.(*ResourceTopologyNodeDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_NodeFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).NodeFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/NodeFailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).NodeFailed(ctx, req.(*ResourceUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_NodeRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).NodeRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/NodeRemoved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).NodeRemoved(ctx, req.(*ResourceUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_NodeUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceTopologyNodeDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).NodeUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/NodeUpdated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).NodeUpdated(ctx, req.(*ResourceTopologyNodeDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_AddTaskStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).AddTaskStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/AddTaskStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).AddTaskStats(ctx, req.(*TaskStats))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_AddNodeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).AddNodeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/AddNodeStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).AddNodeStats(ctx, req.(*ResourceStats))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmamentScheduler_AddTaskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmamentSchedulerServer).AddTaskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmament.FirmamentScheduler/AddTaskInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmamentSchedulerServer).AddTaskInfo(ctx, req.(*TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _FirmamentScheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "firmament.FirmamentScheduler",
	HandlerType: (*FirmamentSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Schedule",
			Handler:    _FirmamentScheduler_Schedule_Handler,
		},
		{
			MethodName: "TaskCompleted",
			Handler:    _FirmamentScheduler_TaskCompleted_Handler,
		},
		{
			MethodName: "TaskFailed",
			Handler:    _FirmamentScheduler_TaskFailed_Handler,
		},
		{
			MethodName: "TaskRemoved",
			Handler:    _FirmamentScheduler_TaskRemoved_Handler,
		},
		{
			MethodName: "TaskSubmitted",
			Handler:    _FirmamentScheduler_TaskSubmitted_Handler,
		},
		{
			MethodName: "TaskUpdated",
			Handler:    _FirmamentScheduler_TaskUpdated_Handler,
		},
		{
			MethodName: "NodeAdded",
			Handler:    _FirmamentScheduler_NodeAdded_Handler,
		},
		{
			MethodName: "NodeFailed",
			Handler:    _FirmamentScheduler_NodeFailed_Handler,
		},
		{
			MethodName: "NodeRemoved",
			Handler:    _FirmamentScheduler_NodeRemoved_Handler,
		},
		{
			MethodName: "NodeUpdated",
			Handler:    _FirmamentScheduler_NodeUpdated_Handler,
		},
		{
			MethodName: "AddTaskStats",
			Handler:    _FirmamentScheduler_AddTaskStats_Handler,
		},
		{
			MethodName: "AddNodeStats",
			Handler:    _FirmamentScheduler_AddNodeStats_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _FirmamentScheduler_Check_Handler,
		},
		{
			MethodName: "AddTaskInfo",
			Handler:    _FirmamentScheduler_AddTaskInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firmament_scheduler.proto",
}

func init() {
	proto.RegisterFile("firmament_scheduler.proto", fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92)
}

var fileDescriptor_firmament_scheduler_3cd4fc8f48cacb92 = []byte{
	// 1161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0xa5, 0x2c, 0xf9, 0x36, 0xb2, 0x25, 0x6a, 0x1c, 0x3b, 0xb2, 0xec, 0xa4, 0x0a, 0x51, 0xa0,
	0xae, 0x53, 0x18, 0x81, 0x8b, 0xa2, 0x40, 0x5f, 0x02, 0x4a, 0xa4, 0x5c, 0xc5, 0xb6, 0x14, 0x90,
	0x92, 0x7b, 0x79, 0x21, 0x68, 0x71, 0x63, 0x33, 0x11, 0x45, 0x96, 0xa4, 0x02, 0xb8, 0x2f, 0xfd,
	0x80, 0xa2, 0xaf, 0xfd, 0x89, 0x7e, 0x54, 0x7f, 0xa5, 0xd8, 0xe5, 0x45, 0x4b, 0x8a, 0x0e, 0x5c,
	0xe7, 0x4d, 0x3c, 0x7b, 0xe6, 0x70, 0xce, 0xec, 0x72, 0x67, 0x04, 0xfb, 0xef, 0x6c, 0xdf, 0x31,
	0x1d, 0x32, 0x0b, 0x8d, 0x60, 0x72, 0x4b, 0xac, 0xf9, 0x94, 0xf8, 0x27, 0x9e, 0xef, 0x86, 0x2e,
	0x6e, 0xa6, 0x4b, 0xad, 0xda, 0x7b, 0xf7, 0xda, 0xb0, 0x48, 0x30, 0x89, 0x96, 0x5a, 0x4f, 0x7c,
	0x12, 0xb8, 0x73, 0x7f, 0x42, 0x8c, 0x20, 0x34, 0xc3, 0x20, 0x46, 0x5f, 0xa4, 0x68, 0xe8, 0x7a,
	0xee, 0xd4, 0xbd, 0xb9, 0x33, 0x66, 0xae, 0x45, 0xf8, 0xc0, 0x7a, 0x68, 0x06, 0x1f, 0x78, 0x40,
	0x64, 0x00, 0xaf, 0xb2, 0x17, 0xe7, 0x61, 0xcf, 0x6e, 0x0c, 0x8b, 0x4c, 0x43, 0x33, 0xc2, 0xa5,
	0x06, 0xd4, 0xf5, 0x38, 0x43, 0x8d, 0xfc, 0x36, 0x27, 0x41, 0x28, 0x05, 0x20, 0xea, 0x29, 0x59,
	0xa1, 0xdc, 0x00, 0x4f, 0x61, 0x8d, 0x45, 0x05, 0xcd, 0x52, 0xbb, 0x7c, 0x54, 0x3d, 0x6d, 0x9d,
	0xa4, 0x36, 0x4e, 0x72, 0x64, 0x2d, 0x66, 0xe2, 0x4b, 0x68, 0xcc, 0x67, 0x89, 0x7d, 0xcb, 0xa0,
	0x29, 0x05, 0xcd, 0x95, 0x76, 0xf9, 0xa8, 0xa2, 0x89, 0xdc, 0xc2, 0x88, 0xe2, 0x92, 0x0a, 0xbb,
	0xf4, 0x47, 0xd7, 0x75, 0xbc, 0x29, 0x09, 0x89, 0xa5, 0x91, 0xc0, 0x73, 0x67, 0x01, 0xc1, 0x6f,
	0xa0, 0x12, 0xde, 0x79, 0xa4, 0x59, 0x6a, 0x97, 0x8e, 0x6a, 0xa7, 0x4d, 0xee, 0xbd, 0x94, 0xaf,
	0x11, 0x6f, 0x7a, 0x37, 0xba, 0xf3, 0x88, 0xc6, 0x58, 0xd2, 0xdf, 0x25, 0xa8, 0x53, 0x5c, 0x21,
	0xc1, 0xc4, 0xb7, 0xbd, 0xd0, 0x76, 0x67, 0xd8, 0x81, 0x45, 0x7d, 0x28, 0xe6, 0xfa, 0x4c, 0xac,
	0x7a, 0xba, 0x9f, 0x13, 0x53, 0x52, 0x82, 0x56, 0x0b, 0x33, 0xcf, 0xf8, 0x1a, 0xd2, 0xcd, 0x8a,
	0x25, 0x56, 0x98, 0x04, 0x9f, 0xcf, 0x1b, 0xf7, 0x9a, 0x53, 0xd8, 0x7e, 0xcf, 0x3f, 0x26, 0xfe,
	0xf4, 0xf9, 0xb5, 0x63, 0x87, 0x8f, 0xf7, 0xd7, 0x85, 0x9d, 0x08, 0x76, 0xdc, 0x8f, 0x8f, 0x16,
	0xe9, 0x00, 0x52, 0xb8, 0x67, 0xda, 0xd3, 0xcf, 0x4d, 0x64, 0xec, 0x59, 0xe6, 0xe3, 0xdd, 0xc8,
	0xd0, 0x18, 0xb8, 0x16, 0x91, 0x2d, 0xeb, 0x41, 0x12, 0x94, 0x5b, 0x90, 0x47, 0x04, 0x3f, 0xb4,
	0x20, 0x45, 0x22, 0x1d, 0x40, 0x0a, 0x3f, 0xb8, 0x20, 0x9f, 0x48, 0xe4, 0xe1, 0x05, 0x29, 0x12,
	0x91, 0xa1, 0xc1, 0x4e, 0x09, 0xfd, 0x70, 0x1f, 0x59, 0x53, 0x15, 0x76, 0xb5, 0xf8, 0xc2, 0x78,
	0xa8, 0x4c, 0x51, 0x26, 0x5f, 0xc2, 0x3a, 0xdb, 0xdf, 0xbe, 0x82, 0xfb, 0xb0, 0xc1, 0xbe, 0x9f,
	0xb9, 0x6d, 0xb1, 0xe0, 0x8a, 0xb6, 0x4e, 0x9f, 0xc7, 0xb6, 0x25, 0xbd, 0x82, 0x6a, 0xf2, 0x32,
	0xca, 0x7c, 0x01, 0x5b, 0xe9, 0x65, 0x95, 0xb0, 0x37, 0xb5, 0x6a, 0x82, 0xd1, 0x88, 0xef, 0x01,
	0x7f, 0x24, 0xe6, 0x34, 0xbc, 0xed, 0xde, 0x92, 0xc9, 0x87, 0xf8, 0xca, 0xa1, 0x81, 0x37, 0xbe,
	0x37, 0x31, 0x02, 0xe2, 0x7f, 0xb4, 0x27, 0x24, 0x09, 0xa4, 0x98, 0x1e, 0x41, 0xd2, 0x19, 0xec,
	0x64, 0x02, 0x63, 0x57, 0xaf, 0x60, 0x8d, 0x5e, 0x73, 0xf3, 0xa0, 0xc0, 0x17, 0x0b, 0x9d, 0xdd,
	0xe8, 0x6c, 0x5d, 0x8b, 0x79, 0xd2, 0x9f, 0x2b, 0xb0, 0x41, 0xad, 0xf5, 0x67, 0xef, 0x5c, 0x3c,
	0x80, 0x4d, 0xe6, 0x6d, 0x66, 0x3a, 0xc9, 0x5b, 0x99, 0xd9, 0x81, 0xe9, 0x10, 0xfc, 0x02, 0xd2,
	0xd4, 0x0d, 0xdb, 0x62, 0x5f, 0xfc, 0xa6, 0x06, 0x09, 0xd4, 0xb7, 0xf0, 0x2b, 0xa8, 0x4f, 0xbc,
	0xb9, 0x31, 0x0f, 0xed, 0xa9, 0xfd, 0xbb, 0x49, 0x2f, 0x9b, 0x66, 0xb9, 0x5d, 0x3a, 0x2a, 0x6b,
	0xb5, 0x89, 0x37, 0x1f, 0x2f, 0x50, 0x4a, 0x74, 0x88, 0x93, 0x21, 0x56, 0x22, 0xa2, 0x43, 0x1c,
	0x9e, 0xd8, 0x81, 0x67, 0xc4, 0xbb, 0x25, 0x0e, 0xf1, 0xcd, 0xa9, 0x11, 0x84, 0xae, 0x6f, 0xde,
	0x90, 0x4c, 0xd8, 0x2a, 0x0b, 0x3b, 0x48, 0x49, 0x7a, 0xc4, 0xe1, 0x35, 0x5e, 0xc6, 0x1b, 0xbd,
	0xc6, 0x0a, 0xf2, 0x34, 0x77, 0x5e, 0xa8, 0x6d, 0x6e, 0x9f, 0x15, 0x10, 0x13, 0x94, 0xab, 0x29,
	0x7f, 0x52, 0x0e, 0x0b, 0x04, 0x72, 0xa7, 0xe5, 0xf8, 0xdf, 0x12, 0x6c, 0x67, 0x0e, 0x23, 0xee,
	0x42, 0x63, 0x24, 0xeb, 0xe7, 0x46, 0x77, 0x78, 0xf9, 0xf6, 0x42, 0x1d, 0xa9, 0x8a, 0x31, 0x3c,
	0x17, 0x85, 0x14, 0xd6, 0xc7, 0x9d, 0xcb, 0xfe, 0x28, 0x86, 0x4b, 0xb8, 0x03, 0x75, 0x06, 0x6b,
	0xea, 0xe5, 0xf0, 0x2a, 0x02, 0x57, 0x10, 0xa1, 0xc6, 0xc0, 0x9e, 0xdc, 0xbf, 0x88, 0xb0, 0x72,
	0x4a, 0x1c, 0xbf, 0x55, 0xe4, 0x38, 0xba, 0x92, 0x12, 0x07, 0xc3, 0x91, 0xd1, 0x1b, 0x8e, 0x07,
	0x8a, 0xb8, 0x8a, 0x7b, 0x80, 0x0c, 0x7b, 0x33, 0xec, 0x70, 0xf8, 0x1a, 0xb6, 0x60, 0x8f, 0xe1,
	0xf2, 0x85, 0xa6, 0xca, 0xca, 0x2f, 0x8b, 0x44, 0xc4, 0xf5, 0x74, 0x4d, 0x1f, 0xc9, 0x23, 0x95,
	0x45, 0x75, 0x35, 0x95, 0xbe, 0x46, 0xdc, 0x38, 0xfe, 0xab, 0x04, 0xdb, 0x99, 0xef, 0x04, 0x1b,
	0xb0, 0x3d, 0x18, 0x2a, 0xaa, 0x21, 0x2b, 0x4a, 0xe2, 0x0e, 0xa1, 0xc6, 0xa0, 0x45, 0xc6, 0xcc,
	0x1a, 0xc3, 0x32, 0xd6, 0x12, 0x90, 0xb3, 0x51, 0x4e, 0xa3, 0x17, 0xe9, 0x56, 0xf0, 0x29, 0xec,
	0x44, 0x2f, 0x89, 0xd3, 0x55, 0x7f, 0xee, 0xeb, 0x23, 0x5d, 0x5c, 0x3d, 0xfe, 0x01, 0xb6, 0x33,
	0xc7, 0x1b, 0xab, 0xb0, 0x3e, 0x1e, 0x9c, 0x0f, 0x86, 0x3f, 0x0d, 0x44, 0x81, 0x3e, 0xe8, 0xaa,
	0x76, 0xd5, 0x1f, 0x9c, 0x89, 0x25, 0xac, 0x43, 0x95, 0x4a, 0x26, 0xc0, 0xca, 0xf1, 0x1f, 0xd1,
	0x2d, 0x93, 0xd9, 0x48, 0xdc, 0x87, 0x5d, 0x6a, 0xbe, 0x3f, 0xe8, 0x0d, 0xb3, 0xbb, 0x23, 0xd0,
	0x24, 0xd2, 0xa5, 0x8c, 0x8d, 0xb8, 0x60, 0x5c, 0x4c, 0x6c, 0x5d, 0x2c, 0x67, 0xd6, 0xa2, 0xa0,
	0x64, 0xad, 0x72, 0xfc, 0x1d, 0x6c, 0xf1, 0x47, 0x11, 0x45, 0xd8, 0x4a, 0xb9, 0xb2, 0xa2, 0x88,
	0x42, 0xb2, 0xcf, 0x5c, 0xb4, 0x58, 0x3a, 0xfd, 0x67, 0x03, 0xb0, 0x97, 0x9c, 0xc5, 0x64, 0x6a,
	0xf1, 0x51, 0x85, 0x8d, 0xe4, 0x01, 0x0b, 0xe6, 0x92, 0x64, 0xae, 0x69, 0x1d, 0xdc, 0x3f, 0xb3,
	0x04, 0x92, 0x80, 0x67, 0xd1, 0x11, 0x4e, 0x27, 0x10, 0xc4, 0xdc, 0xc1, 0x1f, 0xf7, 0x95, 0x56,
	0x3b, 0x87, 0x2d, 0xcd, 0x2b, 0x92, 0x80, 0x32, 0xc0, 0xa2, 0xbd, 0x16, 0xaa, 0x3c, 0xcb, 0x61,
	0xd9, 0xc6, 0x23, 0x09, 0xd8, 0x85, 0x2a, 0xd7, 0xe6, 0x0b, 0x35, 0x9e, 0x2f, 0xf5, 0x81, 0x4c,
	0x07, 0x94, 0x04, 0x1c, 0x46, 0x86, 0xd2, 0x91, 0x23, 0x53, 0x9c, 0xdc, 0x90, 0xb4, 0x64, 0x6c,
	0x69, 0x50, 0x91, 0x04, 0x3c, 0x8f, 0xb2, 0x8a, 0x5b, 0xdc, 0x27, 0xe5, 0xf2, 0xd9, 0xe5, 0xda,
	0xa2, 0x24, 0xe0, 0x15, 0x6c, 0xa6, 0xbd, 0x1f, 0xbf, 0xe6, 0xe8, 0x49, 0x43, 0x19, 0xc5, 0xd3,
	0x2e, 0x65, 0x2d, 0x06, 0xa9, 0xd6, 0x61, 0xae, 0x71, 0x65, 0x86, 0x07, 0x49, 0x40, 0x15, 0x60,
	0xd1, 0xcb, 0x71, 0xaf, 0x40, 0x38, 0xbf, 0x03, 0xcb, 0xad, 0x9f, 0x9d, 0x86, 0x2a, 0x37, 0x57,
	0xdc, 0xab, 0xf3, 0x7c, 0xa9, 0x8d, 0xe6, 0x77, 0xe1, 0xd7, 0x48, 0x28, 0x29, 0xda, 0xff, 0x70,
	0x9a, 0xd7, 0x5e, 0xae, 0xa1, 0x02, 0x5b, 0xb2, 0x65, 0xa5, 0x13, 0x03, 0x3e, 0xc9, 0x6f, 0x22,
	0x45, 0x5b, 0x87, 0x45, 0x28, 0xa7, 0x72, 0xc1, 0x54, 0xe8, 0x1b, 0x22, 0x95, 0x66, 0x41, 0x8a,
	0x91, 0x52, 0xfb, 0xbe, 0x15, 0x4e, 0xad, 0x07, 0xab, 0xac, 0x43, 0x23, 0x5f, 0xe2, 0xe5, 0x96,
	0x9f, 0x71, 0x57, 0xd4, 0xd8, 0x5f, 0x43, 0x35, 0xf6, 0xc6, 0x1a, 0xf5, 0x4e, 0x41, 0x17, 0xca,
	0x7c, 0xd1, 0xf9, 0x2e, 0x76, 0xbd, 0xc6, 0xfe, 0xe0, 0x7c, 0xfb, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xef, 0xe7, 0x84, 0x47, 0x8c, 0x0d, 0x00, 0x00,
}
