/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_desc.proto

package firmament

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceDescriptor_ResourceState int32

const (
	ResourceDescriptor_RESOURCE_UNKNOWN ResourceDescriptor_ResourceState = 0
	ResourceDescriptor_RESOURCE_IDLE    ResourceDescriptor_ResourceState = 1
	ResourceDescriptor_RESOURCE_BUSY    ResourceDescriptor_ResourceState = 2
	ResourceDescriptor_RESOURCE_LOST    ResourceDescriptor_ResourceState = 3
)

var ResourceDescriptor_ResourceState_name = map[int32]string{
	0: "RESOURCE_UNKNOWN",
	1: "RESOURCE_IDLE",
	2: "RESOURCE_BUSY",
	3: "RESOURCE_LOST",
}

var ResourceDescriptor_ResourceState_value = map[string]int32{
	"RESOURCE_UNKNOWN": 0,
	"RESOURCE_IDLE":    1,
	"RESOURCE_BUSY":    2,
	"RESOURCE_LOST":    3,
}

func (x ResourceDescriptor_ResourceState) String() string {
	return proto.EnumName(ResourceDescriptor_ResourceState_name, int32(x))
}

func (ResourceDescriptor_ResourceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eee6351d237bf030, []int{0, 0}
}

type ResourceDescriptor_ResourceType int32

const (
	ResourceDescriptor_RESOURCE_PU          ResourceDescriptor_ResourceType = 0
	ResourceDescriptor_RESOURCE_CORE        ResourceDescriptor_ResourceType = 1
	ResourceDescriptor_RESOURCE_CACHE       ResourceDescriptor_ResourceType = 2
	ResourceDescriptor_RESOURCE_NIC         ResourceDescriptor_ResourceType = 3
	ResourceDescriptor_RESOURCE_DISK        ResourceDescriptor_ResourceType = 4
	ResourceDescriptor_RESOURCE_SSD         ResourceDescriptor_ResourceType = 5
	ResourceDescriptor_RESOURCE_MACHINE     ResourceDescriptor_ResourceType = 6
	ResourceDescriptor_RESOURCE_LOGICAL     ResourceDescriptor_ResourceType = 7
	ResourceDescriptor_RESOURCE_NUMA_NODE   ResourceDescriptor_ResourceType = 8
	ResourceDescriptor_RESOURCE_SOCKET      ResourceDescriptor_ResourceType = 9
	ResourceDescriptor_RESOURCE_COORDINATOR ResourceDescriptor_ResourceType = 10
)

var ResourceDescriptor_ResourceType_name = map[int32]string{
	0:  "RESOURCE_PU",
	1:  "RESOURCE_CORE",
	2:  "RESOURCE_CACHE",
	3:  "RESOURCE_NIC",
	4:  "RESOURCE_DISK",
	5:  "RESOURCE_SSD",
	6:  "RESOURCE_MACHINE",
	7:  "RESOURCE_LOGICAL",
	8:  "RESOURCE_NUMA_NODE",
	9:  "RESOURCE_SOCKET",
	10: "RESOURCE_COORDINATOR",
}

var ResourceDescriptor_ResourceType_value = map[string]int32{
	"RESOURCE_PU":          0,
	"RESOURCE_CORE":        1,
	"RESOURCE_CACHE":       2,
	"RESOURCE_NIC":         3,
	"RESOURCE_DISK":        4,
	"RESOURCE_SSD":         5,
	"RESOURCE_MACHINE":     6,
	"RESOURCE_LOGICAL":     7,
	"RESOURCE_NUMA_NODE":   8,
	"RESOURCE_SOCKET":      9,
	"RESOURCE_COORDINATOR": 10,
}

func (x ResourceDescriptor_ResourceType) String() string {
	return proto.EnumName(ResourceDescriptor_ResourceType_name, int32(x))
}

func (ResourceDescriptor_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eee6351d237bf030, []int{0, 1}
}

type ResourceDescriptor struct {
	Uuid            string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FriendlyName    string `protobuf:"bytes,2,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	DescriptiveName string `protobuf:"bytes,3,opt,name=descriptive_name,json=descriptiveName,proto3" json:"descriptive_name,omitempty"`
	// state is the state of resource.
	State ResourceDescriptor_ResourceState `protobuf:"varint,4,opt,name=state,proto3,enum=firmament.ResourceDescriptor_ResourceState" json:"state,omitempty"`
	// task_capacity is the max number of tasks that can be scheduled on the resource.
	TaskCapacity uint64 `protobuf:"varint,5,opt,name=task_capacity,json=taskCapacity,proto3" json:"task_capacity,omitempty"`
	// last heartbeat of the resource, e.g. node.
	LastHeartbeat uint64 `protobuf:"varint,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// Type of the resource
	Type ResourceDescriptor_ResourceType `protobuf:"varint,7,opt,name=type,proto3,enum=firmament.ResourceDescriptor_ResourceType" json:"type,omitempty"`
	// schedulable indicates if the resource, e.g. node is able to schedule tasks.
	Schedulable bool `protobuf:"varint,8,opt,name=schedulable,proto3" json:"schedulable,omitempty"`
	// current_running_tasks stores all the running tasks on the resource, e.g. node.
	CurrentRunningTasks []uint64 `protobuf:"varint,9,rep,packed,name=current_running_tasks,json=currentRunningTasks,proto3" json:"current_running_tasks,omitempty"`
	// num_running_tasks_below stores the number of running tasks on the resources that are below this node.
	NumRunningTasksBelow uint64 `protobuf:"varint,10,opt,name=num_running_tasks_below,json=numRunningTasksBelow,proto3" json:"num_running_tasks_below,omitempty"`
	NumSlotsBelow        uint64 `protobuf:"varint,11,opt,name=num_slots_below,json=numSlotsBelow,proto3" json:"num_slots_below,omitempty"`
	// Resource capacity and load tracking
	AvailableResources          *ResourceVector `protobuf:"bytes,12,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	ReservedResources           *ResourceVector `protobuf:"bytes,13,opt,name=reserved_resources,json=reservedResources,proto3" json:"reserved_resources,omitempty"`
	MinAvailableResourcesBelow  *ResourceVector `protobuf:"bytes,14,opt,name=min_available_resources_below,json=minAvailableResourcesBelow,proto3" json:"min_available_resources_below,omitempty"`
	MaxAvailableResourcesBelow  *ResourceVector `protobuf:"bytes,15,opt,name=max_available_resources_below,json=maxAvailableResourcesBelow,proto3" json:"max_available_resources_below,omitempty"`
	MinUnreservedResourcesBelow *ResourceVector `protobuf:"bytes,16,opt,name=min_unreserved_resources_below,json=minUnreservedResourcesBelow,proto3" json:"min_unreserved_resources_below,omitempty"`
	MaxUnreservedResourcesBelow *ResourceVector `protobuf:"bytes,17,opt,name=max_unreserved_resources_below,json=maxUnreservedResourcesBelow,proto3" json:"max_unreserved_resources_below,omitempty"`
	ResourceCapacity            *ResourceVector `protobuf:"bytes,18,opt,name=resource_capacity,json=resourceCapacity,proto3" json:"resource_capacity,omitempty"`
	// Cost-model-specific statistics
	WhareMapStats          *WhareMapStats          `protobuf:"bytes,19,opt,name=whare_map_stats,json=whareMapStats,proto3" json:"whare_map_stats,omitempty"`
	CocoInterferenceScores *CoCoInterferenceScores `protobuf:"bytes,20,opt,name=coco_interference_scores,json=cocoInterferenceScores,proto3" json:"coco_interference_scores,omitempty"`
	// Simulation related fields
	TraceMachineId uint64 `protobuf:"varint,21,opt,name=trace_machine_id,json=traceMachineId,proto3" json:"trace_machine_id,omitempty"`
	// Resource labels
	Labels []*Label `protobuf:"bytes,32,rep,name=labels,proto3" json:"labels,omitempty"`
	// Taints
	Taints []*Taint `protobuf:"bytes,33,rep,name=taints,proto3" json:"taints,omitempty"`
	// Max pods allowed per node
	MaxPods              uint64   `protobuf:"varint,34,opt,name=max_pods,json=maxPods,proto3" json:"max_pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceDescriptor) Reset()         { *m = ResourceDescriptor{} }
func (m *ResourceDescriptor) String() string { return proto.CompactTextString(m) }
func (*ResourceDescriptor) ProtoMessage()    {}
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_eee6351d237bf030, []int{0}
}

func (m *ResourceDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceDescriptor.Unmarshal(m, b)
}
func (m *ResourceDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceDescriptor.Marshal(b, m, deterministic)
}
func (m *ResourceDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceDescriptor.Merge(m, src)
}
func (m *ResourceDescriptor) XXX_Size() int {
	return xxx_messageInfo_ResourceDescriptor.Size(m)
}
func (m *ResourceDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceDescriptor proto.InternalMessageInfo

func (m *ResourceDescriptor) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ResourceDescriptor) GetFriendlyName() string {
	if m != nil {
		return m.FriendlyName
	}
	return ""
}

func (m *ResourceDescriptor) GetDescriptiveName() string {
	if m != nil {
		return m.DescriptiveName
	}
	return ""
}

func (m *ResourceDescriptor) GetState() ResourceDescriptor_ResourceState {
	if m != nil {
		return m.State
	}
	return ResourceDescriptor_RESOURCE_UNKNOWN
}

func (m *ResourceDescriptor) GetTaskCapacity() uint64 {
	if m != nil {
		return m.TaskCapacity
	}
	return 0
}

func (m *ResourceDescriptor) GetLastHeartbeat() uint64 {
	if m != nil {
		return m.LastHeartbeat
	}
	return 0
}

func (m *ResourceDescriptor) GetType() ResourceDescriptor_ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceDescriptor_RESOURCE_PU
}

func (m *ResourceDescriptor) GetSchedulable() bool {
	if m != nil {
		return m.Schedulable
	}
	return false
}

func (m *ResourceDescriptor) GetCurrentRunningTasks() []uint64 {
	if m != nil {
		return m.CurrentRunningTasks
	}
	return nil
}

func (m *ResourceDescriptor) GetNumRunningTasksBelow() uint64 {
	if m != nil {
		return m.NumRunningTasksBelow
	}
	return 0
}

func (m *ResourceDescriptor) GetNumSlotsBelow() uint64 {
	if m != nil {
		return m.NumSlotsBelow
	}
	return 0
}

func (m *ResourceDescriptor) GetAvailableResources() *ResourceVector {
	if m != nil {
		return m.AvailableResources
	}
	return nil
}

func (m *ResourceDescriptor) GetReservedResources() *ResourceVector {
	if m != nil {
		return m.ReservedResources
	}
	return nil
}

func (m *ResourceDescriptor) GetMinAvailableResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MinAvailableResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetMaxAvailableResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MaxAvailableResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetMinUnreservedResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MinUnreservedResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetMaxUnreservedResourcesBelow() *ResourceVector {
	if m != nil {
		return m.MaxUnreservedResourcesBelow
	}
	return nil
}

func (m *ResourceDescriptor) GetResourceCapacity() *ResourceVector {
	if m != nil {
		return m.ResourceCapacity
	}
	return nil
}

func (m *ResourceDescriptor) GetWhareMapStats() *WhareMapStats {
	if m != nil {
		return m.WhareMapStats
	}
	return nil
}

func (m *ResourceDescriptor) GetCocoInterferenceScores() *CoCoInterferenceScores {
	if m != nil {
		return m.CocoInterferenceScores
	}
	return nil
}

func (m *ResourceDescriptor) GetTraceMachineId() uint64 {
	if m != nil {
		return m.TraceMachineId
	}
	return 0
}

func (m *ResourceDescriptor) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ResourceDescriptor) GetTaints() []*Taint {
	if m != nil {
		return m.Taints
	}
	return nil
}

func (m *ResourceDescriptor) GetMaxPods() uint64 {
	if m != nil {
		return m.MaxPods
	}
	return 0
}

func init() {
	proto.RegisterEnum("firmament.ResourceDescriptor_ResourceState", ResourceDescriptor_ResourceState_name, ResourceDescriptor_ResourceState_value)
	proto.RegisterEnum("firmament.ResourceDescriptor_ResourceType", ResourceDescriptor_ResourceType_name, ResourceDescriptor_ResourceType_value)
	proto.RegisterType((*ResourceDescriptor)(nil), "firmament.ResourceDescriptor")
}

func init() { proto.RegisterFile("resource_desc.proto", fileDescriptor_eee6351d237bf030) }

var fileDescriptor_eee6351d237bf030 = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xdb, 0x6e, 0xe3, 0x36,
	0x17, 0x85, 0x7f, 0xc7, 0xce, 0x89, 0x3e, 0x31, 0x74, 0x32, 0x3f, 0x27, 0x45, 0x07, 0x9a, 0x14,
	0x2d, 0xd4, 0x16, 0xc8, 0x45, 0x8a, 0xde, 0x16, 0xf5, 0xc8, 0x6e, 0xe3, 0xc6, 0xb1, 0x06, 0x94,
	0xdd, 0x41, 0xd1, 0x62, 0x04, 0x5a, 0x62, 0x1a, 0xa1, 0x16, 0x65, 0x90, 0x54, 0xe2, 0x3c, 0x6e,
	0xdf, 0xa0, 0x8f, 0x50, 0x90, 0x3a, 0x58, 0x1e, 0x4f, 0xc6, 0xbd, 0x8b, 0xd6, 0x5e, 0xfb, 0xd3,
	0xda, 0x8c, 0xb8, 0x0d, 0x7a, 0x82, 0xc9, 0x24, 0x15, 0x01, 0xf3, 0x43, 0x26, 0x83, 0xcb, 0xa5,
	0x48, 0x54, 0x82, 0x8e, 0xef, 0x22, 0x11, 0xd3, 0x98, 0x71, 0x75, 0xfe, 0x2a, 0x48, 0x82, 0xc4,
	0x8f, 0xb8, 0x62, 0xe2, 0x8e, 0x09, 0xc6, 0x03, 0xe6, 0xcb, 0x20, 0x11, 0x4c, 0x66, 0xd6, 0xf3,
	0xe6, 0x82, 0xce, 0xd9, 0x22, 0x7f, 0x38, 0x2b, 0x61, 0x0f, 0x2c, 0x50, 0x89, 0x28, 0xe4, 0xc7,
	0x7b, 0x2a, 0x98, 0x1f, 0xd3, 0xa5, 0x2f, 0x15, 0x55, 0x45, 0x6b, 0x4b, 0xd1, 0x88, 0x17, 0x4f,
	0x17, 0x7f, 0xb7, 0x01, 0x22, 0x79, 0xfb, 0x80, 0xc9, 0x40, 0x44, 0x4b, 0x95, 0x08, 0x84, 0x40,
	0x23, 0x4d, 0xa3, 0x10, 0xd7, 0xac, 0x9a, 0x7d, 0x4c, 0xcc, 0xdf, 0xe8, 0x0b, 0xd0, 0xbe, 0x13,
	0x11, 0xe3, 0xe1, 0xe2, 0xc9, 0xe7, 0x34, 0x66, 0x78, 0xcf, 0x14, 0x5b, 0x85, 0x38, 0xa1, 0x31,
	0x43, 0x5f, 0x03, 0x18, 0xe6, 0x98, 0xe8, 0x81, 0x65, 0xbe, 0xba, 0xf1, 0x75, 0x2b, 0xba, 0xb1,
	0xf6, 0xc1, 0xbe, 0xce, 0xc5, 0x70, 0xc3, 0xaa, 0xd9, 0x9d, 0xab, 0x6f, 0x2f, 0xcb, 0xf1, 0x2f,
	0xb7, 0x13, 0x95, 0x92, 0xa7, 0x5b, 0x48, 0xd6, 0xa9, 0x23, 0x29, 0x2a, 0xff, 0xf2, 0x03, 0xba,
	0xa4, 0x41, 0xa4, 0x9e, 0xf0, 0xbe, 0x55, 0xb3, 0x1b, 0xa4, 0xa5, 0x45, 0x27, 0xd7, 0xd0, 0x97,
	0xa0, 0xb3, 0xa0, 0x52, 0xf9, 0xf7, 0x8c, 0x0a, 0x35, 0x67, 0x54, 0xe1, 0x03, 0xe3, 0x6a, 0x6b,
	0xf5, 0xba, 0x10, 0xd1, 0x0f, 0xa0, 0xa1, 0x9e, 0x96, 0x0c, 0x1f, 0x9a, 0x34, 0xdf, 0xfc, 0xb7,
	0x34, 0xd3, 0xa7, 0x25, 0x23, 0xa6, 0x0f, 0x59, 0xa0, 0x29, 0x83, 0x7b, 0x16, 0xa6, 0x0b, 0x3a,
	0x5f, 0x30, 0x7c, 0x64, 0xd5, 0xec, 0x23, 0x52, 0x95, 0xd0, 0x15, 0x38, 0x0b, 0x52, 0x21, 0x18,
	0x57, 0xbe, 0x48, 0x39, 0x8f, 0xf8, 0x9f, 0xbe, 0x0e, 0x2a, 0xf1, 0xb1, 0x55, 0xb7, 0x1b, 0xa4,
	0x97, 0x17, 0x49, 0x56, 0x9b, 0xea, 0x12, 0xfa, 0x1e, 0xfc, 0x9f, 0xa7, 0xf1, 0xa6, 0xdf, 0x9f,
	0xb3, 0x45, 0xf2, 0x88, 0x81, 0x99, 0xe2, 0x94, 0xa7, 0x71, 0xb5, 0xe3, 0x8d, 0xae, 0xa1, 0xaf,
	0x40, 0x57, 0xb7, 0xc9, 0x45, 0xa2, 0x0a, 0x7b, 0x33, 0x1b, 0x9a, 0xa7, 0xb1, 0xa7, 0xd5, 0xcc,
	0xf7, 0x0b, 0xe8, 0xd1, 0x07, 0x1a, 0x99, 0x7c, 0x7e, 0xf1, 0x19, 0x49, 0xdc, 0xb2, 0x6a, 0x76,
	0xf3, 0xea, 0xe5, 0x47, 0xce, 0xe0, 0x57, 0xf3, 0x85, 0x11, 0x54, 0x76, 0x15, 0x05, 0x89, 0xae,
	0x01, 0x12, 0x4c, 0x32, 0xf1, 0xc0, 0xc2, 0x0a, 0xaa, 0xbd, 0x0b, 0x75, 0x52, 0x34, 0xad, 0x49,
	0x7f, 0x80, 0xcf, 0xe3, 0x88, 0xfb, 0x1f, 0x49, 0x96, 0xcf, 0xd2, 0xd9, 0x05, 0x3d, 0x8f, 0x23,
	0xde, 0xdf, 0x8a, 0x98, 0xcd, 0xac, 0xe9, 0x74, 0xf5, 0x09, 0x7a, 0x77, 0x37, 0x9d, 0xae, 0x9e,
	0xa3, 0xbf, 0x07, 0xaf, 0x74, 0xf6, 0x94, 0x6f, 0x9f, 0x45, 0x8e, 0x87, 0xbb, 0xf0, 0x9f, 0xc5,
	0x11, 0x9f, 0xf1, 0xad, 0x63, 0x59, 0xf3, 0xe9, 0xea, 0x53, 0xfc, 0x93, 0xdd, 0x7c, 0xba, 0x7a,
	0x96, 0xff, 0x13, 0x38, 0x29, 0xd7, 0x49, 0x79, 0xad, 0xd0, 0x2e, 0x24, 0x2c, 0x7a, 0xca, 0x5b,
	0xf7, 0x23, 0xe8, 0x7e, 0xb0, 0x7f, 0x70, 0xcf, 0x50, 0x70, 0x85, 0xf2, 0x4e, 0x3b, 0x6e, 0xe9,
	0x52, 0x5f, 0x6a, 0x49, 0xda, 0x8f, 0xd5, 0x47, 0xf4, 0x3b, 0xc0, 0xcf, 0x6d, 0x41, 0x7c, 0x6a,
	0x50, 0xaf, 0x2b, 0x28, 0x27, 0x71, 0x92, 0x51, 0xc5, 0xe9, 0x19, 0x23, 0x79, 0xa1, 0x11, 0xdb,
	0x3a, 0xb2, 0x01, 0x54, 0x82, 0x06, 0x3a, 0x5e, 0x70, 0x1f, 0x71, 0xe6, 0x47, 0x21, 0x3e, 0x33,
	0x37, 0xa4, 0x63, 0xf4, 0xdb, 0x4c, 0x1e, 0x85, 0xc8, 0x06, 0x07, 0x66, 0xd9, 0x4a, 0x6c, 0x59,
	0x75, 0xbb, 0x79, 0x05, 0x2b, 0x2f, 0x1d, 0xeb, 0x02, 0xc9, 0xeb, 0xda, 0x99, 0xed, 0x56, 0xfc,
	0x7a, 0xcb, 0x39, 0xd5, 0x05, 0x92, 0xd7, 0xd1, 0x4b, 0x70, 0xa4, 0xff, 0x89, 0xcb, 0x24, 0x94,
	0xf8, 0xc2, 0xbc, 0xf5, 0x30, 0xa6, 0xab, 0xb7, 0x49, 0x28, 0x2f, 0xde, 0x83, 0xf6, 0xc6, 0xaa,
	0x43, 0xa7, 0x00, 0x92, 0xa1, 0xe7, 0xce, 0x88, 0x33, 0xf4, 0x67, 0x93, 0x9b, 0x89, 0xfb, 0x6e,
	0x02, 0xff, 0x87, 0x4e, 0x40, 0xbb, 0x54, 0x47, 0x83, 0xf1, 0x10, 0xd6, 0x36, 0xa4, 0x37, 0x33,
	0xef, 0x37, 0xb8, 0xb7, 0x21, 0x8d, 0x5d, 0x6f, 0x0a, 0xeb, 0x17, 0xff, 0xd4, 0x40, 0xab, 0xba,
	0xbd, 0x50, 0x17, 0x34, 0x4b, 0xcf, 0xdb, 0xd9, 0x07, 0x68, 0xc7, 0x25, 0x1a, 0x8d, 0x40, 0x67,
	0x2d, 0xf5, 0x9d, 0xeb, 0x21, 0xdc, 0x43, 0x10, 0xb4, 0x4a, 0x6d, 0x32, 0x72, 0x60, 0x7d, 0xa3,
	0x71, 0x30, 0xf2, 0x6e, 0x60, 0x63, 0xc3, 0xe4, 0x79, 0x03, 0xb8, 0xbf, 0x31, 0xce, 0x6d, 0xdf,
	0xb9, 0x1e, 0x4d, 0x86, 0xf0, 0x60, 0x43, 0x1d, 0xbb, 0x3f, 0x8f, 0x9c, 0xfe, 0x18, 0x1e, 0xa2,
	0x17, 0x00, 0xad, 0x5f, 0x31, 0xbb, 0xed, 0xfb, 0x13, 0x77, 0x30, 0x84, 0x47, 0xa8, 0x07, 0xba,
	0x6b, 0xaa, 0xeb, 0xdc, 0x0c, 0xa7, 0xf0, 0x18, 0x61, 0x70, 0x5a, 0x89, 0xed, 0x92, 0xc1, 0x68,
	0xd2, 0x9f, 0xba, 0x04, 0x82, 0xf9, 0x81, 0xf9, 0xa9, 0xfb, 0xee, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa5, 0x0e, 0x51, 0x3e, 0x75, 0x07, 0x00, 0x00,
}
