/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task_final_report.proto

package firmament

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// TaskFinalReport describes the final state of a task in firmament scheduler.
type TaskFinalReport struct {
	TaskId       uint64  `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	StartTime    uint64  `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	FinishTime   uint64  `protobuf:"varint,3,opt,name=finish_time,json=finishTime" json:"finish_time,omitempty"`
	Instructions uint64  `protobuf:"varint,4,opt,name=instructions" json:"instructions,omitempty"`
	Cycles       uint64  `protobuf:"varint,5,opt,name=cycles" json:"cycles,omitempty"`
	LlcRefs      uint64  `protobuf:"varint,6,opt,name=llc_refs,json=llcRefs" json:"llc_refs,omitempty"`
	LlcMisses    uint64  `protobuf:"varint,7,opt,name=llc_misses,json=llcMisses" json:"llc_misses,omitempty"`
	Runtime      float64 `protobuf:"fixed64,8,opt,name=runtime" json:"runtime,omitempty"`
}

func (m *TaskFinalReport) Reset()                    { *m = TaskFinalReport{} }
func (m *TaskFinalReport) String() string            { return proto.CompactTextString(m) }
func (*TaskFinalReport) ProtoMessage()               {}
func (*TaskFinalReport) Descriptor() ([]byte, []int) { return fileDescriptor17, []int{0} }

func (m *TaskFinalReport) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskFinalReport) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TaskFinalReport) GetFinishTime() uint64 {
	if m != nil {
		return m.FinishTime
	}
	return 0
}

func (m *TaskFinalReport) GetInstructions() uint64 {
	if m != nil {
		return m.Instructions
	}
	return 0
}

func (m *TaskFinalReport) GetCycles() uint64 {
	if m != nil {
		return m.Cycles
	}
	return 0
}

func (m *TaskFinalReport) GetLlcRefs() uint64 {
	if m != nil {
		return m.LlcRefs
	}
	return 0
}

func (m *TaskFinalReport) GetLlcMisses() uint64 {
	if m != nil {
		return m.LlcMisses
	}
	return 0
}

func (m *TaskFinalReport) GetRuntime() float64 {
	if m != nil {
		return m.Runtime
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskFinalReport)(nil), "firmament.TaskFinalReport")
}

func init() { proto.RegisterFile("task_final_report.proto", fileDescriptor17) }

var fileDescriptor17 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x89, 0x9e, 0xbb, 0x77, 0xa3, 0x20, 0xa4, 0xf0, 0x62, 0x21, 0x1e, 0x57, 0x5d, 0x65,
	0xe3, 0x7f, 0x10, 0x2c, 0x6c, 0x96, 0xeb, 0x97, 0x98, 0x4b, 0x70, 0xb8, 0x24, 0x7b, 0xcc, 0xcc,
	0x16, 0xfe, 0x75, 0x2b, 0xd9, 0x09, 0x16, 0x96, 0xef, 0x7d, 0x5f, 0xc8, 0x63, 0x60, 0x2b, 0x9e,
	0xcf, 0x63, 0xc2, 0xea, 0xf3, 0x48, 0xf1, 0x32, 0x91, 0xbc, 0x5c, 0x68, 0x92, 0xc9, 0x6e, 0x12,
	0x52, 0xf1, 0x25, 0x56, 0xd9, 0xff, 0x18, 0xb8, 0x3f, 0x7a, 0x3e, 0xbf, 0x2d, 0xd6, 0xa0, 0x92,
	0xdd, 0x42, 0xaf, 0x2f, 0xf1, 0xe4, 0xcc, 0xce, 0x1c, 0x56, 0x43, 0xb7, 0xc4, 0xf7, 0x93, 0x7d,
	0x02, 0x60, 0xf1, 0x24, 0xa3, 0x60, 0x89, 0xee, 0x4a, 0xd9, 0x46, 0x9b, 0x23, 0x96, 0x68, 0x9f,
	0xe1, 0x36, 0x61, 0x45, 0xfe, 0x6a, 0xfc, 0x5a, 0x39, 0xb4, 0x4a, 0x85, 0x3d, 0xdc, 0x61, 0x65,
	0xa1, 0x39, 0x08, 0x4e, 0x95, 0xdd, 0x4a, 0x8d, 0x7f, 0x9d, 0x7d, 0x80, 0x2e, 0x7c, 0x87, 0x1c,
	0xd9, 0xdd, 0xb4, 0xbf, 0x5b, 0xb2, 0x8f, 0xb0, 0xce, 0x39, 0x8c, 0x14, 0x13, 0xbb, 0x4e, 0x49,
	0x9f, 0x73, 0x18, 0x62, 0xe2, 0x65, 0xd6, 0x82, 0x0a, 0x32, 0x47, 0x76, 0x7d, 0x9b, 0x95, 0x73,
	0xf8, 0xd0, 0xc2, 0x3a, 0xe8, 0x69, 0xae, 0x3a, 0x69, 0xbd, 0x33, 0x07, 0x33, 0xfc, 0xc5, 0xcf,
	0x4e, 0xcf, 0xf1, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x8a, 0x77, 0xae, 0x29, 0x01, 0x00,
	0x00,
}
